package com.moons.xst.track.bean;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WORK__BILL.
 */
public class Work_Bill implements BaseSearch, Serializable{

    private Integer Work_Bill_ID;
    private String Work_Bill_Code;
    private String Work_Begin_Time;
    private String Work_End_Time;
    private Integer Tache_ID;
    private Integer JD_ID;
    private String Work_Bill_Type_TX;
    private String Work_Bill_TaskContent_TX;
    private String Work_Bill_Memo_TX;
    private String Work_Bill_Operator;
    private String Work_Bill_Guardian;
    private String Work_Bill_Watch;
    private String Work_Bill_Duty;
    private String ID_CD;
    private String Place_TX;

    public Work_Bill() {
    }

    public Work_Bill(Integer Work_Bill_ID) {
        this.Work_Bill_ID = Work_Bill_ID;
    }

    public Work_Bill(Integer Work_Bill_ID, String Work_Bill_Code, String Work_Begin_Time, String Work_End_Time, Integer Tache_ID, Integer JD_ID, String Work_Bill_Type_TX, String Work_Bill_TaskContent_TX, String Work_Bill_Memo_TX, String Work_Bill_Operator, String Work_Bill_Guardian, String Work_Bill_Watch, String Work_Bill_Duty, String ID_CD, String Place_TX) {
        this.Work_Bill_ID = Work_Bill_ID;
        this.Work_Bill_Code = Work_Bill_Code;
        this.Work_Begin_Time = Work_Begin_Time;
        this.Work_End_Time = Work_End_Time;
        this.Tache_ID = Tache_ID;
        this.JD_ID = JD_ID;
        this.Work_Bill_Type_TX = Work_Bill_Type_TX;
        this.Work_Bill_TaskContent_TX = Work_Bill_TaskContent_TX;
        this.Work_Bill_Memo_TX = Work_Bill_Memo_TX;
        this.Work_Bill_Operator = Work_Bill_Operator;
        this.Work_Bill_Guardian = Work_Bill_Guardian;
        this.Work_Bill_Watch = Work_Bill_Watch;
        this.Work_Bill_Duty = Work_Bill_Duty;
        this.ID_CD = ID_CD;
        this.Place_TX = Place_TX;
    }

    public Integer getWork_Bill_ID() {
        return Work_Bill_ID;
    }

    public void setWork_Bill_ID(Integer Work_Bill_ID) {
        this.Work_Bill_ID = Work_Bill_ID;
    }

    public String getWork_Bill_Code() {
        return Work_Bill_Code;
    }

    public void setWork_Bill_Code(String Work_Bill_Code) {
        this.Work_Bill_Code = Work_Bill_Code;
    }

    public String getWork_Begin_Time() {
        return Work_Begin_Time;
    }

    public void setWork_Begin_Time(String Work_Begin_Time) {
        this.Work_Begin_Time = Work_Begin_Time;
    }

    public String getWork_End_Time() {
        return Work_End_Time;
    }

    public void setWork_End_Time(String Work_End_Time) {
        this.Work_End_Time = Work_End_Time;
    }

    public Integer getTache_ID() {
        return Tache_ID;
    }

    public void setTache_ID(Integer Tache_ID) {
        this.Tache_ID = Tache_ID;
    }

    public Integer getJD_ID() {
        return JD_ID;
    }

    public void setJD_ID(Integer JD_ID) {
        this.JD_ID = JD_ID;
    }

    public String getWork_Bill_Type_TX() {
        return Work_Bill_Type_TX;
    }

    public void setWork_Bill_Type_TX(String Work_Bill_Type_TX) {
        this.Work_Bill_Type_TX = Work_Bill_Type_TX;
    }

    public String getWork_Bill_TaskContent_TX() {
        return Work_Bill_TaskContent_TX;
    }

    public void setWork_Bill_TaskContent_TX(String Work_Bill_TaskContent_TX) {
        this.Work_Bill_TaskContent_TX = Work_Bill_TaskContent_TX;
    }

    public String getWork_Bill_Memo_TX() {
        return Work_Bill_Memo_TX;
    }

    public void setWork_Bill_Memo_TX(String Work_Bill_Memo_TX) {
        this.Work_Bill_Memo_TX = Work_Bill_Memo_TX;
    }

    public String getWork_Bill_Operator() {
        return Work_Bill_Operator;
    }

    public void setWork_Bill_Operator(String Work_Bill_Operator) {
        this.Work_Bill_Operator = Work_Bill_Operator;
    }

    public String getWork_Bill_Guardian() {
        return Work_Bill_Guardian;
    }

    public void setWork_Bill_Guardian(String Work_Bill_Guardian) {
        this.Work_Bill_Guardian = Work_Bill_Guardian;
    }

    public String getWork_Bill_Watch() {
        return Work_Bill_Watch;
    }

    public void setWork_Bill_Watch(String Work_Bill_Watch) {
        this.Work_Bill_Watch = Work_Bill_Watch;
    }

    public String getWork_Bill_Duty() {
        return Work_Bill_Duty;
    }

    public void setWork_Bill_Duty(String Work_Bill_Duty) {
        this.Work_Bill_Duty = Work_Bill_Duty;
    }

    public String getID_CD() {
        return ID_CD;
    }

    public void setID_CD(String ID_CD) {
        this.ID_CD = ID_CD;
    }

    public String getPlace_TX() {
        return Place_TX;
    }

    public void setPlace_TX(String Place_TX) {
        this.Place_TX = Place_TX;
    }

	@Override
	public String getSearchCondition() {
		 StringBuilder searchStr = new StringBuilder();
	        searchStr.append(Work_Bill_TaskContent_TX);
	        return searchStr.toString();
	}

}
