package com.moons.xst.sqlite;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;

import com.moons.xst.track.bean.OverhaulPlan;
import com.moons.xst.track.bean.OverhaulProject;
import com.moons.xst.track.bean.OverhaulUser;
import com.moons.xst.track.dao.OverhaulPlanDao;
import com.moons.xst.track.dao.OverhaulProjectDao;
import com.moons.xst.track.dao.OverhaulUserDao;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class OverhaulDaoSession extends AbstractDaoSession {

    private final DaoConfig jX_UserDaoConfig;
    private final DaoConfig jX_JXPlanHNYNDaoConfig;
    private final DaoConfig jX_WorkOrderForHNYNDaoConfig;

    private final OverhaulUserDao jX_UserDao;
    private final OverhaulPlanDao jX_JXPlanHNYNDao;
    private final OverhaulProjectDao jX_WorkOrderForHNYNDao;

    public OverhaulDaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        jX_UserDaoConfig = daoConfigMap.get(OverhaulUserDao.class).clone();
        jX_UserDaoConfig.initIdentityScope(type);

        jX_JXPlanHNYNDaoConfig = daoConfigMap.get(OverhaulPlanDao.class).clone();
        jX_JXPlanHNYNDaoConfig.initIdentityScope(type);

        jX_WorkOrderForHNYNDaoConfig = daoConfigMap.get(OverhaulProjectDao.class).clone();
        jX_WorkOrderForHNYNDaoConfig.initIdentityScope(type);

        jX_UserDao = new OverhaulUserDao(jX_UserDaoConfig, this);
        jX_JXPlanHNYNDao = new OverhaulPlanDao(jX_JXPlanHNYNDaoConfig, this);
        jX_WorkOrderForHNYNDao = new OverhaulProjectDao(jX_WorkOrderForHNYNDaoConfig, this);

        registerDao(OverhaulUser.class, jX_UserDao);
        registerDao(OverhaulPlan.class, jX_JXPlanHNYNDao);
        registerDao(OverhaulProject.class, jX_WorkOrderForHNYNDao);
    }
    
    public void clear() {
        jX_UserDaoConfig.getIdentityScope().clear();
        jX_JXPlanHNYNDaoConfig.getIdentityScope().clear();
        jX_WorkOrderForHNYNDaoConfig.getIdentityScope().clear();
    }

    public OverhaulUserDao getOverhaulUserDao() {
        return jX_UserDao;
    }

    public OverhaulPlanDao getOverhaulPlanDao() {
        return jX_JXPlanHNYNDao;
    }

    public OverhaulProjectDao getOverhaulProjectDao() {
        return jX_WorkOrderForHNYNDao;
    }

}
