package com.moons.xst.track.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LKLINE_TREE_BY_IDPOS.
 */
public class LKLineTreeByIDPos {

    /** Not-null value. */
    private String IDPos_ID;
    /** Not-null value. */
    private String LKControlPoint_ID;
    /** Not-null value. */
    private String Name_TX;

    public LKLineTreeByIDPos() {
    }

    public LKLineTreeByIDPos(String IDPos_ID, String LKControlPoint_ID, String Name_TX) {
        this.IDPos_ID = IDPos_ID;
        this.LKControlPoint_ID = LKControlPoint_ID;
        this.Name_TX = Name_TX;
    }

    /** Not-null value. */
    public String getIDPos_ID() {
        return IDPos_ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIDPos_ID(String IDPos_ID) {
        this.IDPos_ID = IDPos_ID;
    }

    /** Not-null value. */
    public String getLKControlPoint_ID() {
        return LKControlPoint_ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLKControlPoint_ID(String LKControlPoint_ID) {
        this.LKControlPoint_ID = LKControlPoint_ID;
    }

    /** Not-null value. */
    public String getName_TX() {
        return Name_TX;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName_TX(String Name_TX) {
        this.Name_TX = Name_TX;
    }

}
