package com.moons.xst.track.bean;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DJ__CONTROL_POINT.
 */
public class DJ_ControlPoint {

	/** Not-null value. */
	private String ControlPoint_ID;
	/** Not-null value. */
	private String Name_TX;
	private boolean SRPlan_YN;
	private boolean LKPlan_YN;
	private int SortNo_NR;
	/** Not-null value. */
	private String LastSRResult_TM;
	/** Not-null value. */
	private String LastSRResult_TX;
	/** Not-null value. */
	private String TransInfo_TX;

	private int srPlanCount = 0;

	private boolean isCurrSR = false;

	public DJ_ControlPoint() {
	}

	public DJ_ControlPoint(String ControlPoint_ID, String Name_TX,
			boolean SRPlan_YN, boolean LKPlan_YN, int SortNo_NR,
			String LastSRResult_TM, String LastSRResult_TX, String TransInfo_TX) {
		this.ControlPoint_ID = ControlPoint_ID;
		this.Name_TX = Name_TX;
		this.SRPlan_YN = SRPlan_YN;
		this.LKPlan_YN = LKPlan_YN;
		this.SortNo_NR = SortNo_NR;
		this.LastSRResult_TM = LastSRResult_TM;
		this.LastSRResult_TX = LastSRResult_TX;
		this.TransInfo_TX = TransInfo_TX;
	}

	/** Not-null value. */
	public String getControlPoint_ID() {
		return ControlPoint_ID;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setControlPoint_ID(String ControlPoint_ID) {
		this.ControlPoint_ID = ControlPoint_ID;
	}

	/** Not-null value. */
	public String getName_TX() {
		return Name_TX;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setName_TX(String Name_TX) {
		this.Name_TX = Name_TX;
	}

	public boolean getSRPlan_YN() {
		return SRPlan_YN;
	}

	public void setSRPlan_YN(boolean SRPlan_YN) {
		this.SRPlan_YN = SRPlan_YN;
	}

	public boolean getLKPlan_YN() {
		return LKPlan_YN;
	}

	public void setLKPlan_YN(boolean LKPlan_YN) {
		this.LKPlan_YN = LKPlan_YN;
	}

	public int getSortNo_NR() {
		return SortNo_NR;
	}

	public void setSortNo_NR(int SortNo_NR) {
		this.SortNo_NR = SortNo_NR;
	}

	/** Not-null value. */
	public String getLastSRResult_TM() {
		return LastSRResult_TM;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setLastSRResult_TM(String LastSRResult_TM) {
		this.LastSRResult_TM = LastSRResult_TM;
	}

	/** Not-null value. */
	public String getLastSRResult_TX() {
		return LastSRResult_TX;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setLastSRResult_TX(String LastSRResult_TX) {
		this.LastSRResult_TX = LastSRResult_TX;
	}

	/** Not-null value. */
	public String getTransInfo_TX() {
		return TransInfo_TX;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setTransInfo_TX(String TransInfo_TX) {
		this.TransInfo_TX = TransInfo_TX;
	}

	public int getSRPlanCount() {
		return srPlanCount;
	}

	public void setSRPlanCount(int count) {
		this.srPlanCount = count;
	}

	public void setisCurrSR(boolean yn) {
		this.isCurrSR = yn;
	}

	public boolean getisCurrSR() {
		return isCurrSR;
	}
}
