package com.moons.xst.track.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GPSPOSITION.
 */
public class ComGPSPosition {

    /** Not-null value. */
    private String XJQGUID_TX;
    /** Not-null value. */
    private String XJQ_CD;
    /** Not-null value. */
    private String Line_ID;
    /** Not-null value. */
    private String AppUser_CD;
    /** Not-null value. */
    private String AppUserName_TX;
    /** Not-null value. */
    private String ID_CD;
    /** Not-null value. */
    private String Place_TX;
    /** Not-null value. */
    private String Longitude_TX;
    /** Not-null value. */
    private String Latitude_TX;
    /** Not-null value. */
    private String UTC_DT;
    /** Not-null value. */
    private String GPSDISTANCE_TX;
    /** Not-null value. */
    private String GPSCOSTTIME_TX;
    /** Not-null value. */
    private String GPSPOINTTYPE_TX;

    public ComGPSPosition() {
    }

    public ComGPSPosition(String XJQGUID_TX) {
        this.XJQGUID_TX = XJQGUID_TX;
    }

    public ComGPSPosition(String XJQGUID_TX, String XJQ_CD, String Line_ID, String AppUser_CD, String AppUserName_TX, String ID_CD, String Place_TX, String Longitude_TX, String Latitude_TX, String UTC_DT, String GPSDISTANCE_TX, String GPSCOSTTIME_TX, String GPSPOINTTYPE_TX) {
        this.XJQGUID_TX = XJQGUID_TX;
        this.XJQ_CD = XJQ_CD;
        this.Line_ID = Line_ID;
        this.AppUser_CD = AppUser_CD;
        this.AppUserName_TX = AppUserName_TX;
        this.ID_CD = ID_CD;
        this.Place_TX = Place_TX;
        this.Longitude_TX = Longitude_TX;
        this.Latitude_TX = Latitude_TX;
        this.UTC_DT = UTC_DT;
        this.GPSDISTANCE_TX = GPSDISTANCE_TX;
        this.GPSCOSTTIME_TX = GPSCOSTTIME_TX;
        this.GPSPOINTTYPE_TX = GPSPOINTTYPE_TX;
    }

    /** Not-null value. */
    public String getXJQGUID_TX() {
        return XJQGUID_TX;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setXJQGUID_TX(String XJQGUID_TX) {
        this.XJQGUID_TX = XJQGUID_TX;
    }

    /** Not-null value. */
    public String getXJQ_CD() {
        return XJQ_CD;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setXJQ_CD(String XJQ_CD) {
        this.XJQ_CD = XJQ_CD;
    }

    /** Not-null value. */
    public String getLine_ID() {
        return Line_ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLine_ID(String Line_ID) {
        this.Line_ID = Line_ID;
    }

    /** Not-null value. */
    public String getAppUser_CD() {
        return AppUser_CD;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAppUser_CD(String AppUser_CD) {
        this.AppUser_CD = AppUser_CD;
    }

    /** Not-null value. */
    public String getAppUserName_TX() {
        return AppUserName_TX;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAppUserName_TX(String AppUserName_TX) {
        this.AppUserName_TX = AppUserName_TX;
    }

    /** Not-null value. */
    public String getID_CD() {
        return ID_CD;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setID_CD(String ID_CD) {
        this.ID_CD = ID_CD;
    }

    /** Not-null value. */
    public String getPlace_TX() {
        return Place_TX;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlace_TX(String Place_TX) {
        this.Place_TX = Place_TX;
    }

    /** Not-null value. */
    public String getLongitude_TX() {
        return Longitude_TX;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLongitude_TX(String Longitude_TX) {
        this.Longitude_TX = Longitude_TX;
    }

    /** Not-null value. */
    public String getLatitude_TX() {
        return Latitude_TX;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLatitude_TX(String Latitude_TX) {
        this.Latitude_TX = Latitude_TX;
    }

    /** Not-null value. */
    public String getUTC_DT() {
        return UTC_DT;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUTC_DT(String UTC_DT) {
        this.UTC_DT = UTC_DT;
    }

    /** Not-null value. */
    public String getGPSDISTANCE_TX() {
        return GPSDISTANCE_TX;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGPSDISTANCE_TX(String GPSDISTANCE_TX) {
        this.GPSDISTANCE_TX = GPSDISTANCE_TX;
    }

    /** Not-null value. */
    public String getGPSCOSTTIME_TX() {
        return GPSCOSTTIME_TX;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGPSCOSTTIME_TX(String GPSCOSTTIME_TX) {
        this.GPSCOSTTIME_TX = GPSCOSTTIME_TX;
    }

    /** Not-null value. */
    public String getGPSPOINTTYPE_TX() {
        return GPSPOINTTYPE_TX;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGPSPOINTTYPE_TX(String GPSPOINTTYPE_TX) {
        this.GPSPOINTTYPE_TX = GPSPOINTTYPE_TX;
    }

}
