package com.moons.xst.track.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Z__CONDITION.
 */
public class Z_Condition {

    /** Not-null value. */
    private String Condition_id;
    private String ParentCon_id;
    private String ConName_TX;
    private String ConValue_TX;
    private String ConType_TX;
    private String ConLevel_TX;
    private String TransInfo_TX;
    private String LevelNum_TX;
    private String Sort_TX;

    public Z_Condition() {
    }

    public Z_Condition(String Condition_id, String ParentCon_id, String ConName_TX, String ConValue_TX, String ConType_TX, String ConLevel_TX, String TransInfo_TX, String LevelNum_TX, String Sort_TX) {
        this.Condition_id = Condition_id;
        this.ParentCon_id = ParentCon_id;
        this.ConName_TX = ConName_TX;
        this.ConValue_TX = ConValue_TX;
        this.ConType_TX = ConType_TX;
        this.ConLevel_TX = ConLevel_TX;
        this.TransInfo_TX = TransInfo_TX;
        this.LevelNum_TX = LevelNum_TX;
        this.Sort_TX = Sort_TX;
    }

    /** Not-null value. */
    public String getCondition_id() {
        return Condition_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCondition_id(String Condition_id) {
        this.Condition_id = Condition_id;
    }

    public String getParentCon_id() {
        return ParentCon_id;
    }

    public void setParentCon_id(String ParentCon_id) {
        this.ParentCon_id = ParentCon_id;
    }

    public String getConName_TX() {
        return ConName_TX;
    }

    public void setConName_TX(String ConName_TX) {
        this.ConName_TX = ConName_TX;
    }

    public String getConValue_TX() {
        return ConValue_TX;
    }

    public void setConValue_TX(String ConValue_TX) {
        this.ConValue_TX = ConValue_TX;
    }

    public String getConType_TX() {
        return ConType_TX;
    }

    public void setConType_TX(String ConType_TX) {
        this.ConType_TX = ConType_TX;
    }

    public String getConLevel_TX() {
        return ConLevel_TX;
    }

    public void setConLevel_TX(String ConLevel_TX) {
        this.ConLevel_TX = ConLevel_TX;
    }

    public String getTransInfo_TX() {
        return TransInfo_TX;
    }

    public void setTransInfo_TX(String TransInfo_TX) {
        this.TransInfo_TX = TransInfo_TX;
    }

    public String getLevelNum_TX() {
        return LevelNum_TX;
    }

    public void setLevelNum_TX(String LevelNum_TX) {
        this.LevelNum_TX = LevelNum_TX;
    }

    public String getSort_TX() {
        return Sort_TX;
    }

    public void setSort_TX(String Sort_TX) {
        this.Sort_TX = Sort_TX;
    }

}
