package com.moons.xst.track.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Z__SHIFT.
 */
public class Z_Shift {

    /** Not-null value. */
    private String Shift_CD;
    /** Not-null value. */
    private String Name_TX;
    /** Not-null value. */
    private String StartTime_TX;
    /** Not-null value. */
    private String EndTime_TX;
    private String RStartTime_TX;
    private String REndTime_TX;

    public Z_Shift() {
    }

    public Z_Shift(String Shift_CD, String Name_TX, String StartTime_TX, String EndTime_TX, String RStartTime_TX, String REndTime_TX) {
        this.Shift_CD = Shift_CD;
        this.Name_TX = Name_TX;
        this.StartTime_TX = StartTime_TX;
        this.EndTime_TX = EndTime_TX;
        this.RStartTime_TX = RStartTime_TX;
        this.REndTime_TX = REndTime_TX;
    }

    /** Not-null value. */
    public String getShift_CD() {
        return Shift_CD;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setShift_CD(String Shift_CD) {
        this.Shift_CD = Shift_CD;
    }

    /** Not-null value. */
    public String getName_TX() {
        return Name_TX;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName_TX(String Name_TX) {
        this.Name_TX = Name_TX;
    }

    /** Not-null value. */
    public String getStartTime_TX() {
        return StartTime_TX;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStartTime_TX(String StartTime_TX) {
        this.StartTime_TX = StartTime_TX;
    }

    /** Not-null value. */
    public String getEndTime_TX() {
        return EndTime_TX;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEndTime_TX(String EndTime_TX) {
        this.EndTime_TX = EndTime_TX;
    }

    public String getRStartTime_TX() {
        return RStartTime_TX;
    }

    public void setRStartTime_TX(String RStartTime_TX) {
        this.RStartTime_TX = RStartTime_TX;
    }

    public String getREndTime_TX() {
        return REndTime_TX;
    }

    public void setREndTime_TX(String REndTime_TX) {
        this.REndTime_TX = REndTime_TX;
    }

}
