package com.moons.xst.track.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DJ__PHOTO_BY_RESULT.
 */
public class DJ_PhotoByResult {

	/** Not-null value. */
	private String DJ_Plan_ID;
	/** Not-null value. */
	private String Partition_ID;
	/** Not-null value. */
	private String Photo_DT;
	/** Not-null value. */
	private String GUID;
	/** Not-null value. */
	private String LCType;

	private String File_Bytes = "";// 图片和录音的内容

	public DJ_PhotoByResult() {
	}

	public DJ_PhotoByResult(String DJ_Plan_ID, String Partition_ID,
			String Photo_DT, String GUID, String LCType) {
		this.DJ_Plan_ID = DJ_Plan_ID;
		this.Partition_ID = Partition_ID;
		this.Photo_DT = Photo_DT;
		this.GUID = GUID;
		this.LCType = LCType;
	}
	/** Not-null value. */
	public String getDJ_Plan_ID() {
		return DJ_Plan_ID;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setDJ_Plan_ID(String DJ_Plan_ID) {
		this.DJ_Plan_ID = DJ_Plan_ID;
	}

	/** Not-null value. */
	public String getPartition_ID() {
		return Partition_ID;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setPartition_ID(String Partition_ID) {
		this.Partition_ID = Partition_ID;
	}

	/** Not-null value. */
	public String getPhoto_DT() {
		return Photo_DT;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setPhoto_DT(String Photo_DT) {
		this.Photo_DT = Photo_DT;
	}

	/** Not-null value. */
	public String getGUID() {
		return GUID;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setGUID(String GUID) {
		this.GUID = GUID;
	}

	/** Not-null value. */
	public String getLCType() {
		return LCType;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setLCType(String LCType) {
		this.LCType = LCType;
	}

	private String _filePath;

	public void setFilePath(String filePath) {
		_filePath = filePath;
	}

	public String getFilePath() {
		return _filePath;
	}

	private String _filetitle = "";

	public void setFileTitle(String filePath) {
		_filetitle = filePath;
	}

	public String getFileTitle() {
		return _filetitle;
	}

	public void setFile_Bytes(String File_Bytes) {
		this.File_Bytes = File_Bytes;
	}

	public String getFile_Bytes() {
		return File_Bytes;
	}
}
