package com.moons.xst.track.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DJ__RESULT_HIS.
 */
public class DJ_ResultHis {
	
	 /** Not-null value. */
//    private Integer Line_ID;
    /** Not-null value. */
    private String DJ_Plan_ID;
    /** Not-null value. */
    private String CompleteTime_DT;
    /** Not-null value. */
//    private String PlanDesc_TX;
    /** Not-null value. */
//    private String IDPosName_TX;
    private String AppUser_CD;
    private String AppUserName_TX;
    /** Not-null value. */
    private String Result_TX;
    private byte[] Data8K_TX;
    /** Not-null value. */
    private String Query_DT;
    private String MObjectStateName_TX;
    /** Not-null value. */
    private String Exception_YN;
    private Integer AlarmLevel_ID;
    /** Not-null value. */
    private String SpecCase_YN;
    private String SpecCase_TX;
    private String Memo_TX;
    private int Time_NR;
    /** Not-null value. */
    private String DataFlag_CD;
    private String ShiftName_TX;
    private String ShiftGroupName_TX;
    private Boolean Ratio_NR;
    private String Ratio1_NR;
    private Integer Rate;
    private Integer DataLen;
    private String LastResult_TX;
    private String TransInfo_TX;
    private String VibParam_TX;
    private String FeatureValue_TX;
    private String GPSInfo_TX;

    public DJ_ResultHis() {
    }

    public DJ_ResultHis(String DJ_Plan_ID, String CompleteTime_DT, String AppUser_CD, String AppUserName_TX, String Result_TX, byte[] Data8K_TX, String Query_DT, String MObjectStateName_TX, String Exception_YN, Integer AlarmLevel_ID, String SpecCase_YN, String SpecCase_TX, String Memo_TX, int Time_NR, String DataFlag_CD, String ShiftName_TX, String ShiftGroupName_TX, Boolean Ratio_NR, String Ratio1_NR, Integer Rate, Integer DataLen, String LastResult_TX, String TransInfo_TX, String VibParam_TX, String FeatureValue_TX, String GPSInfo_TX) {
//    	this.Line_ID = Line_ID;
        this.DJ_Plan_ID = DJ_Plan_ID;
        this.CompleteTime_DT = CompleteTime_DT;
//        this.PlanDesc_TX = PlanDesc_TX;
//        this.IDPosName_TX =IDPosName_TX ;
        this.AppUser_CD = AppUser_CD;
        this.AppUserName_TX = AppUserName_TX;
        this.Result_TX = Result_TX;
        this.Data8K_TX = Data8K_TX;
        this.Query_DT = Query_DT;
        this.MObjectStateName_TX = MObjectStateName_TX;
        this.Exception_YN = Exception_YN;
        this.AlarmLevel_ID = AlarmLevel_ID;
        this.SpecCase_YN = SpecCase_YN;
        this.SpecCase_TX = SpecCase_TX;
        this.Memo_TX = Memo_TX;
        this.Time_NR = Time_NR;
        this.DataFlag_CD = DataFlag_CD;
        this.ShiftName_TX = ShiftName_TX;
        this.ShiftGroupName_TX = ShiftGroupName_TX;
        this.Ratio_NR = Ratio_NR;
        this.Ratio1_NR = Ratio1_NR;
        this.Rate = Rate;
        this.DataLen = DataLen;
        this.LastResult_TX = LastResult_TX;
        this.TransInfo_TX = TransInfo_TX;
        this.VibParam_TX = VibParam_TX;
        this.FeatureValue_TX = FeatureValue_TX;
        this.GPSInfo_TX = GPSInfo_TX;
    }

    /** Not-null value. */
//    public Integer getLine_ID() {
//        return Line_ID;
//    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
//    public void setLine_ID(Integer Line_ID) {
//        this.Line_ID = Line_ID;
//    }
    /** Not-null value. */
    public String getDJ_Plan_ID() {
        return DJ_Plan_ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDJ_Plan_ID(String DJ_Plan_ID) {
        this.DJ_Plan_ID = DJ_Plan_ID;
    }

    /** Not-null value. */
    public String getCompleteTime_DT() {
        return CompleteTime_DT;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompleteTime_DT(String CompleteTime_DT) {
        this.CompleteTime_DT = CompleteTime_DT;
    }
    /** Not-null value. */
//    public String getPlanDesc_TX() {
//        return PlanDesc_TX;
//    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
//    public void setPlanDesc_TX(String PlanDesc_TX) {
//        this.PlanDesc_TX = PlanDesc_TX;
//    } 
    /** Not-null value. */
//    public String getIDPosName_TX() {
//        return IDPosName_TX;
//    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
//    public void setIDPosName_TX(String IDPosName_TX) {
//        this.IDPosName_TX = IDPosName_TX;
//    }
    /** Not-null value. */
    public String getAppUser_CD() {
        return AppUser_CD;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAppUser_CD(String AppUser_CD) {
        this.AppUser_CD = AppUser_CD;
    }

    public String getAppUserName_TX() {
        return AppUserName_TX;
    }

    public void setAppUserName_TX(String AppUserName_TX) {
        this.AppUserName_TX = AppUserName_TX;
    }

    /** Not-null value. */
    public String getResult_TX() {
        return Result_TX;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setResult_TX(String Result_TX) {
        this.Result_TX = Result_TX;
    }

    public byte[] getData8K_TX() {
        return Data8K_TX;
    }

    public void setData8K_TX(byte[] Data8K_TX) {
        this.Data8K_TX = Data8K_TX;
    }

    /** Not-null value. */
    public String getQuery_DT() {
        return Query_DT;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setQuery_DT(String Query_DT) {
        this.Query_DT = Query_DT;
    }

    public String getMObjectStateName_TX() {
        return MObjectStateName_TX;
    }

    public void setMObjectStateName_TX(String MObjectStateName_TX) {
        this.MObjectStateName_TX = MObjectStateName_TX;
    }

    /** Not-null value. */
    public String getException_YN() {
        return Exception_YN;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setException_YN(String Exception_YN) {
        this.Exception_YN = Exception_YN;
    }

    public Integer getAlarmLevel_ID() {
        return AlarmLevel_ID;
    }

    public void setAlarmLevel_ID(Integer AlarmLevel_ID) {
        this.AlarmLevel_ID = AlarmLevel_ID;
    }

    /** Not-null value. */
    public String getSpecCase_YN() {
        return SpecCase_YN;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSpecCase_YN(String SpecCase_YN) {
        this.SpecCase_YN = SpecCase_YN;
    }

    public String getSpecCase_TX() {
        return SpecCase_TX;
    }

    public void setSpecCase_TX(String SpecCase_TX) {
        this.SpecCase_TX = SpecCase_TX;
    }

    public String getMemo_TX() {
        return Memo_TX;
    }

    public void setMemo_TX(String Memo_TX) {
        this.Memo_TX = Memo_TX;
    }

    public int getTime_NR() {
        return Time_NR;
    }

    public void setTime_NR(int Time_NR) {
        this.Time_NR = Time_NR;
    }

    /** Not-null value. */
    public String getDataFlag_CD() {
        return DataFlag_CD;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDataFlag_CD(String DataFlag_CD) {
        this.DataFlag_CD = DataFlag_CD;
    }

    public String getShiftName_TX() {
        return ShiftName_TX;
    }

    public void setShiftName_TX(String ShiftName_TX) {
        this.ShiftName_TX = ShiftName_TX;
    }

    public String getShiftGroupName_TX() {
        return ShiftGroupName_TX;
    }

    public void setShiftGroupName_TX(String ShiftGroupName_TX) {
        this.ShiftGroupName_TX = ShiftGroupName_TX;
    }

    public Boolean getRatio_NR() {
        return Ratio_NR;
    }

    public void setRatio_NR(Boolean Ratio_NR) {
        this.Ratio_NR = Ratio_NR;
    }

    public String getRatio1_NR() {
        return Ratio1_NR;
    }

    public void setRatio1_NR(String Ratio1_NR) {
        this.Ratio1_NR = Ratio1_NR;
    }

    public Integer getRate() {
        return Rate;
    }

    public void setRate(Integer Rate) {
        this.Rate = Rate;
    }

    public Integer getDataLen() {
        return DataLen;
    }

    public void setDataLen(Integer DataLen) {
        this.DataLen = DataLen;
    }

    public String getLastResult_TX() {
        return LastResult_TX;
    }

    public void setLastResult_TX(String LastResult_TX) {
        this.LastResult_TX = LastResult_TX;
    }

    public String getTransInfo_TX() {
        return TransInfo_TX;
    }

    public void setTransInfo_TX(String TransInfo_TX) {
        this.TransInfo_TX = TransInfo_TX;
    }

    public String getVibParam_TX() {
        return VibParam_TX;
    }

    public void setVibParam_TX(String VibParam_TX) {
        this.VibParam_TX = VibParam_TX;
    }

    public String getFeatureValue_TX() {
        return FeatureValue_TX;
    }

    public void setFeatureValue_TX(String FeatureValue_TX) {
        this.FeatureValue_TX = FeatureValue_TX;
    }

    public String getGPSInfo_TX() {
        return GPSInfo_TX;
    }

    public void setGPSInfo_TX(String GPSInfo_TX) {
        this.GPSInfo_TX = GPSInfo_TX;
    }

}
