package com.moons.xst.track.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GPSMOBJECT_BUG_RESULT_HIS.
 */
public class GPSMobjectBugResultHis {

    /** Not-null value. */
    private String Result_ID;
    private int Type_ID;
    private int GZDM_ID;
    private int ZZDM_ID;
    private int YYDM_ID;
    private int CSDM_ID;
    private int GPSPoint_ID;
    private String BugMemo_TX;
    /** Not-null value. */
    private String Find_TM;
    private int Post_ID;
    /** Not-null value. */
    private String FindUser_TX;
    /** Not-null value. */
    private String Longitude;
    /** Not-null value. */
    private String Latitude;

    public GPSMobjectBugResultHis() {
    }

    public GPSMobjectBugResultHis(String Result_ID, int Type_ID, int GZDM_ID, int ZZDM_ID, int YYDM_ID, int CSDM_ID, int GPSPoint_ID, String BugMemo_TX, String Find_TM, int Post_ID, String FindUser_TX, String Longitude, String Latitude) {
        this.Result_ID = Result_ID;
        this.Type_ID = Type_ID;
        this.GZDM_ID = GZDM_ID;
        this.ZZDM_ID = ZZDM_ID;
        this.YYDM_ID = YYDM_ID;
        this.CSDM_ID = CSDM_ID;
        this.GPSPoint_ID = GPSPoint_ID;
        this.BugMemo_TX = BugMemo_TX;
        this.Find_TM = Find_TM;
        this.Post_ID = Post_ID;
        this.FindUser_TX = FindUser_TX;
        this.Longitude = Longitude;
        this.Latitude = Latitude;
    }

    /** Not-null value. */
    public String getResult_ID() {
        return Result_ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setResult_ID(String Result_ID) {
        this.Result_ID = Result_ID;
    }

    public int getType_ID() {
        return Type_ID;
    }

    public void setType_ID(int Type_ID) {
        this.Type_ID = Type_ID;
    }

    public int getGZDM_ID() {
        return GZDM_ID;
    }

    public void setGZDM_ID(int GZDM_ID) {
        this.GZDM_ID = GZDM_ID;
    }

    public int getZZDM_ID() {
        return ZZDM_ID;
    }

    public void setZZDM_ID(int ZZDM_ID) {
        this.ZZDM_ID = ZZDM_ID;
    }

    public int getYYDM_ID() {
        return YYDM_ID;
    }

    public void setYYDM_ID(int YYDM_ID) {
        this.YYDM_ID = YYDM_ID;
    }

    public int getCSDM_ID() {
        return CSDM_ID;
    }

    public void setCSDM_ID(int CSDM_ID) {
        this.CSDM_ID = CSDM_ID;
    }

    public int getGPSPoint_ID() {
        return GPSPoint_ID;
    }

    public void setGPSPoint_ID(int GPSPoint_ID) {
        this.GPSPoint_ID = GPSPoint_ID;
    }

    public String getBugMemo_TX() {
        return BugMemo_TX;
    }

    public void setBugMemo_TX(String BugMemo_TX) {
        this.BugMemo_TX = BugMemo_TX;
    }

    /** Not-null value. */
    public String getFind_TM() {
        return Find_TM;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFind_TM(String Find_TM) {
        this.Find_TM = Find_TM;
    }

    public int getPost_ID() {
        return Post_ID;
    }

    public void setPost_ID(int Post_ID) {
        this.Post_ID = Post_ID;
    }

    /** Not-null value. */
    public String getFindUser_TX() {
        return FindUser_TX;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFindUser_TX(String FindUser_TX) {
        this.FindUser_TX = FindUser_TX;
    }

    /** Not-null value. */
    public String getLongitude() {
        return Longitude;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLongitude(String Longitude) {
        this.Longitude = Longitude;
    }

    /** Not-null value. */
    public String getLatitude() {
        return Latitude;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLatitude(String Latitude) {
        this.Latitude = Latitude;
    }

}
