package com.moons.xst.track.bean;

import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GPSMOBJECT_BUG_RESULT.
 */
public class GPSMobjectBugResult {

	private String Result_ID;
	private int Type_ID;
	private int GZDM_ID;
	private int ZZDM_ID;
	private int YYDM_ID;
	private int CSDM_ID;
	private int GPSPoint_ID;
	private String BugMemo_TX;
	/** Not-null value. */
	private String Find_TM;
	private int Post_ID;
	/** Not-null value. */
	private String FindUser_TX;
	/** Not-null value. */
	private String Longitude;
	/** Not-null value. */
	private String Latitude;
    private String EventType_ID;
    private String EventName_TX;
    private String SBPost_ID;
    private String GX_ID;
    private String GXName_TX;
    private String EventPlace_TX;
    private String EventStatus_ID;
    private String SBType_ID;
	private List<GPSMobjectBugResultForFiles> BugFiles;

	public GPSMobjectBugResult() {
	}

	   public GPSMobjectBugResult(String Result_ID, Integer Type_ID, Integer GZDM_ID, Integer ZZDM_ID, Integer YYDM_ID, Integer CSDM_ID, Integer GPSPoint_ID, String BugMemo_TX, String Find_TM, Integer Post_ID, String FindUser_TX, String Longitude, String Latitude, String EventType_ID, String EventName_TX, String SBPost_ID, String GX_ID, String GXName_TX, String EventPlace_TX, String EventStatus_ID, String SBType_ID) {
	        this.Result_ID = Result_ID;
	        this.Type_ID = Type_ID;
	        this.GZDM_ID = GZDM_ID;
	        this.ZZDM_ID = ZZDM_ID;
	        this.YYDM_ID = YYDM_ID;
	        this.CSDM_ID = CSDM_ID;
	        this.GPSPoint_ID = GPSPoint_ID;
	        this.BugMemo_TX = BugMemo_TX;
	        this.Find_TM = Find_TM;
	        this.Post_ID = Post_ID;
	        this.FindUser_TX = FindUser_TX;
	        this.Longitude = Longitude;
	        this.Latitude = Latitude;
	        this.EventType_ID = EventType_ID;
	        this.EventName_TX = EventName_TX;
	        this.SBPost_ID = SBPost_ID;
	        this.GX_ID = GX_ID;
	        this.GXName_TX = GXName_TX;
	        this.EventPlace_TX = EventPlace_TX;
	        this.EventStatus_ID = EventStatus_ID;
	        this.SBType_ID = SBType_ID;
	    }


	public String getResult_ID() {
		return Result_ID;
	}

	public void setResult_ID(String Result_ID) {
		this.Result_ID = Result_ID;
	}

	public int getType_ID() {
		return Type_ID;
	}

	public void setType_ID(int Type_ID) {
		this.Type_ID = Type_ID;
	}

	public int getGZDM_ID() {
		return GZDM_ID;
	}

	public void setGZDM_ID(int GZDM_ID) {
		this.GZDM_ID = GZDM_ID;
	}

	public int getZZDM_ID() {
		return ZZDM_ID;
	}

	public void setZZDM_ID(int ZZDM_ID) {
		this.ZZDM_ID = ZZDM_ID;
	}

	public int getYYDM_ID() {
		return YYDM_ID;
	}

	public void setYYDM_ID(int YYDM_ID) {
		this.YYDM_ID = YYDM_ID;
	}

	public int getCSDM_ID() {
		return CSDM_ID;
	}

	public void setCSDM_ID(int CSDM_ID) {
		this.CSDM_ID = CSDM_ID;
	}

	public int getGPSPoint_ID() {
		return GPSPoint_ID;
	}

	public void setGPSPoint_ID(int GPSPoint_ID) {
		this.GPSPoint_ID = GPSPoint_ID;
	}

	public String getBugMemo_TX() {
		return BugMemo_TX;
	}

	public void setBugMemo_TX(String BugMemo_TX) {
		this.BugMemo_TX = BugMemo_TX;
	}

	/** Not-null value. */
	public String getFind_TM() {
		return Find_TM;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setFind_TM(String Find_TM) {
		this.Find_TM = Find_TM;
	}

	public int getPost_ID() {
		return Post_ID;
	}

	public void setPost_ID(int Post_ID) {
		this.Post_ID = Post_ID;
	}

	/** Not-null value. */
	public String getFindUser_TX() {
		return FindUser_TX;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setFindUser_TX(String FindUser_TX) {
		this.FindUser_TX = FindUser_TX;
	}

	/** Not-null value. */
	public String getLongitude() {
		return Longitude;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setLongitude(String Longitude) {
		this.Longitude = Longitude;
	}

	/** Not-null value. */
	public String getLatitude() {
		return Latitude;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setLatitude(String Latitude) {
		this.Latitude = Latitude;
	}

    public String getEventType_ID() {
        return EventType_ID;
    }

    public void setEventType_ID(String EventType_ID) {
        this.EventType_ID = EventType_ID;
    }

    public String getEventName_TX() {
        return EventName_TX;
    }

    public void setEventName_TX(String EventName_TX) {
        this.EventName_TX = EventName_TX;
    }

    public String getSBPost_ID() {
        return SBPost_ID;
    }

    public void setSBPost_ID(String SBPost_ID) {
        this.SBPost_ID = SBPost_ID;
    }

    public String getGX_ID() {
        return GX_ID;
    }

    public void setGX_ID(String GX_ID) {
        this.GX_ID = GX_ID;
    }

    public String getGXName_TX() {
        return GXName_TX;
    }

    public void setGXName_TX(String GXName_TX) {
        this.GXName_TX = GXName_TX;
    }

    public String getEventPlace_TX() {
        return EventPlace_TX;
    }

    public void setEventPlace_TX(String EventPlace_TX) {
        this.EventPlace_TX = EventPlace_TX;
    }

    public String getEventStatus_ID() {
        return EventStatus_ID;
    }

    public void setEventStatus_ID(String EventStatus_ID) {
        this.EventStatus_ID = EventStatus_ID;
    }

    public String getSBType_ID() {
        return SBType_ID;
    }

    public void setSBType_ID(String SBType_ID) {
        this.SBType_ID = SBType_ID;
    }
	
	public void setBugFiles(List<GPSMobjectBugResultForFiles> bugFiles) {
		BugFiles = bugFiles;
	}

	public List<GPSMobjectBugResultForFiles> getBugFiles() {
		return BugFiles;
	}

}
