package com.moons.xst.track.bean;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table JX_USER.
 */
public class OverhaulUser implements Serializable {

    /** Not-null value. */
    private String AppUser_ID;
    private String AppUser_CD;
    /** Not-null value. */
    private String AppAccount_TX;
    /** Not-null value. */
    private String Name_TX;
    private String XJQPWD_TX;
    private Integer DEPT_ID;
    private String DEPT_CD;
    private String DEPTNAME_TX;

    public OverhaulUser() {
    }

    public OverhaulUser(String AppUser_ID, String AppUser_CD, String AppAccount_TX, String Name_TX, String XJQPWD_TX, Integer DEPT_ID, String DEPT_CD, String DEPTNAME_TX) {
        this.AppUser_ID = AppUser_ID;
        this.AppUser_CD = AppUser_CD;
        this.AppAccount_TX = AppAccount_TX;
        this.Name_TX = Name_TX;
        this.XJQPWD_TX = XJQPWD_TX;
        this.DEPT_ID = DEPT_ID;
        this.DEPT_CD = DEPT_CD;
        this.DEPTNAME_TX = DEPTNAME_TX;
    }

    /** Not-null value. */
    public String getAppUser_ID() {
        return AppUser_ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAppUser_ID(String AppUser_ID) {
        this.AppUser_ID = AppUser_ID;
    }

    public String getAppUser_CD() {
        return AppUser_CD;
    }

    public void setAppUser_CD(String AppUser_CD) {
        this.AppUser_CD = AppUser_CD;
    }

    /** Not-null value. */
    public String getAppAccount_TX() {
        return AppAccount_TX;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAppAccount_TX(String AppAccount_TX) {
        this.AppAccount_TX = AppAccount_TX;
    }

    /** Not-null value. */
    public String getName_TX() {
        return Name_TX;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName_TX(String Name_TX) {
        this.Name_TX = Name_TX;
    }

    public String getXJQPWD_TX() {
        return XJQPWD_TX;
    }

    public void setXJQPWD_TX(String XJQPWD_TX) {
        this.XJQPWD_TX = XJQPWD_TX;
    }

    public Integer getDEPT_ID() {
        return DEPT_ID;
    }

    public void setDEPT_ID(Integer DEPT_ID) {
        this.DEPT_ID = DEPT_ID;
    }

    public String getDEPT_CD() {
        return DEPT_CD;
    }

    public void setDEPT_CD(String DEPT_CD) {
        this.DEPT_CD = DEPT_CD;
    }

    public String getDEPTNAME_TX() {
        return DEPTNAME_TX;
    }

    public void setDEPTNAME_TX(String DEPTNAME_TX) {
        this.DEPTNAME_TX = DEPTNAME_TX;
    }

}
