package com.moons.xst.track.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RH__TASK_ACTIVE.
 */
public class RH_TaskActive {

    /** Not-null value. */
    private String RHTask_ID;
    private String IDPos_ID;
    private int SortNo_NR;
    /** Not-null value. */
    private String PStart_DT;
    /** Not-null value. */
    private String PEnd_DT;
    private String WorkContent_TX;
    /** Not-null value. */
    private String TaskMethod_CD;
    private String Memo_TX;
    private Integer DealWithUser_ID;
    private String DealWith_DT;

    public RH_TaskActive() {
    }

    public RH_TaskActive(String RHTask_ID, String IDPos_ID, int SortNo_NR, String PStart_DT, String PEnd_DT, String WorkContent_TX, String TaskMethod_CD, String Memo_TX, Integer DealWithUser_ID, String DealWith_DT) {
        this.RHTask_ID = RHTask_ID;
        this.IDPos_ID = IDPos_ID;
        this.SortNo_NR = SortNo_NR;
        this.PStart_DT = PStart_DT;
        this.PEnd_DT = PEnd_DT;
        this.WorkContent_TX = WorkContent_TX;
        this.TaskMethod_CD = TaskMethod_CD;
        this.Memo_TX = Memo_TX;
        this.DealWithUser_ID = DealWithUser_ID;
        this.DealWith_DT = DealWith_DT;
    }

    /** Not-null value. */
    public String getRHTask_ID() {
        return RHTask_ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRHTask_ID(String RHTask_ID) {
        this.RHTask_ID = RHTask_ID;
    }

    public String getIDPos_ID() {
        return IDPos_ID;
    }

    public void setIDPos_ID(String IDPos_ID) {
        this.IDPos_ID = IDPos_ID;
    }

    public int getSortNo_NR() {
        return SortNo_NR;
    }

    public void setSortNo_NR(int SortNo_NR) {
        this.SortNo_NR = SortNo_NR;
    }

    /** Not-null value. */
    public String getPStart_DT() {
        return PStart_DT;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPStart_DT(String PStart_DT) {
        this.PStart_DT = PStart_DT;
    }

    /** Not-null value. */
    public String getPEnd_DT() {
        return PEnd_DT;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPEnd_DT(String PEnd_DT) {
        this.PEnd_DT = PEnd_DT;
    }

    public String getWorkContent_TX() {
        return WorkContent_TX;
    }

    public void setWorkContent_TX(String WorkContent_TX) {
        this.WorkContent_TX = WorkContent_TX;
    }

    /** Not-null value. */
    public String getTaskMethod_CD() {
        return TaskMethod_CD;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTaskMethod_CD(String TaskMethod_CD) {
        this.TaskMethod_CD = TaskMethod_CD;
    }

    public String getMemo_TX() {
        return Memo_TX;
    }

    public void setMemo_TX(String Memo_TX) {
        this.Memo_TX = Memo_TX;
    }

    public Integer getDealWithUser_ID() {
        return DealWithUser_ID;
    }

    public void setDealWithUser_ID(Integer DealWithUser_ID) {
        this.DealWithUser_ID = DealWithUser_ID;
    }

    public String getDealWith_DT() {
        return DealWith_DT;
    }

    public void setDealWith_DT(String DealWith_DT) {
        this.DealWith_DT = DealWith_DT;
    }

}
