package com.moons.xst.track.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Z__APP_USER.
 */
public class Z_AppUser {

    /** Not-null value. */
    private String AppUser_ID;
    private String AppAccount_TX;
    /** Not-null value. */
    private String AppUser_CD;
    /** Not-null value. */
    private String Name_TX;
    private String XJQPWD_TX;
    private String LastVisitDate_DT;
    private String EncrytionType_TX;

    public Z_AppUser() {
    }

    public Z_AppUser(String AppUser_ID, String AppAccount_TX, String AppUser_CD, String Name_TX, String XJQPWD_TX, String LastVisitDate_DT, String EncrytionType_TX) {
        this.AppUser_ID = AppUser_ID;
        this.AppAccount_TX = AppAccount_TX;
        this.AppUser_CD = AppUser_CD;
        this.Name_TX = Name_TX;
        this.XJQPWD_TX = XJQPWD_TX;
        this.LastVisitDate_DT = LastVisitDate_DT;
        this.EncrytionType_TX = EncrytionType_TX;
    }

    /** Not-null value. */
    public String getAppUser_ID() {
        return AppUser_ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAppUser_ID(String AppUser_ID) {
        this.AppUser_ID = AppUser_ID;
    }

    public String getAppAccount_TX() {
        return AppAccount_TX;
    }

    public void setAppAccount_TX(String AppAccount_TX) {
        this.AppAccount_TX = AppAccount_TX;
    }

    /** Not-null value. */
    public String getAppUser_CD() {
        return AppUser_CD;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAppUser_CD(String AppUser_CD) {
        this.AppUser_CD = AppUser_CD;
    }

    /** Not-null value. */
    public String getName_TX() {
        return Name_TX;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName_TX(String Name_TX) {
        this.Name_TX = Name_TX;
    }

    public String getXJQPWD_TX() {
        return XJQPWD_TX;
    }

    public void setXJQPWD_TX(String XJQPWD_TX) {
        this.XJQPWD_TX = XJQPWD_TX;
    }

    public String getLastVisitDate_DT() {
        return LastVisitDate_DT;
    }

    public void setLastVisitDate_DT(String LastVisitDate_DT) {
        this.LastVisitDate_DT = LastVisitDate_DT;
    }

    public String getEncrytionType_TX() {
        return EncrytionType_TX;
    }

    public void setEncrytionType_TX(String EncrytionType_TX) {
        this.EncrytionType_TX = EncrytionType_TX;
    }

}
