package com.moons.xst.track.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Z__SHIFT_RULE.
 */
public class Z_ShiftRule {

    /** Not-null value. */
    private String Work_DT;
    /** Not-null value. */
    private String Shift_CD;
    /** Not-null value. */
    private String ShiftGroup_CD;

    public Z_ShiftRule() {
    }

    public Z_ShiftRule(String Work_DT, String Shift_CD, String ShiftGroup_CD) {
        this.Work_DT = Work_DT;
        this.Shift_CD = Shift_CD;
        this.ShiftGroup_CD = ShiftGroup_CD;
    }

    /** Not-null value. */
    public String getWork_DT() {
        return Work_DT;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setWork_DT(String Work_DT) {
        this.Work_DT = Work_DT;
    }

    /** Not-null value. */
    public String getShift_CD() {
        return Shift_CD;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setShift_CD(String Shift_CD) {
        this.Shift_CD = Shift_CD;
    }

    /** Not-null value. */
    public String getShiftGroup_CD() {
        return ShiftGroup_CD;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setShiftGroup_CD(String ShiftGroup_CD) {
        this.ShiftGroup_CD = ShiftGroup_CD;
    }

}
