package com.moons.xst.track.bean;
// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Z__SPEC_CASE.
 */
public class Z_SpecCase {

    /** Not-null value. */
    private String SpecCase_ID;
    /** Not-null value. */
    private String Name_TX;

    public Z_SpecCase() {
    }

    public Z_SpecCase(String SpecCase_ID, String Name_TX) {
        this.SpecCase_ID = SpecCase_ID;
        this.Name_TX = Name_TX;
    }

    /** Not-null value. */
    public String getSpecCase_ID() {
        return SpecCase_ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSpecCase_ID(String SpecCase_ID) {
        this.SpecCase_ID = SpecCase_ID;
    }

    /** Not-null value. */
    public String getName_TX() {
        return Name_TX;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName_TX(String Name_TX) {
        this.Name_TX = Name_TX;
    }

}
