package com.moons.xst.track.bean;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table JX_JXPLAN_HNYN.
 */
public class OverhaulPlan implements BaseSearch,Serializable {

    private int JXPlan_ID;
    /** Not-null value. */
    private String JXPlan_CD;
    private Integer Area_ID;
    private Integer Spec_ID;
    private int ZYX_ID;
    private int JXType_ID;
    /** Not-null value. */
    private String PlanName_TX;
    /** Not-null value. */
    private String PlanContent_TX;
    /** Not-null value. */
    private String PlanStart_DT;
    /** Not-null value. */
    private String PlanEnd_DT;
    private int AddPost_ID;
    /** Not-null value. */
    private String Add_DT;
    /** Not-null value. */
    private String AddUserName_TX;
    private String Edit_DT;
    private String EditUserName_TX;
    private boolean isFinished;

    public OverhaulPlan() {
    }

    public OverhaulPlan(int JXPlan_ID, String JXPlan_CD, Integer Area_ID, Integer Spec_ID, int ZYX_ID, int JXType_ID, String PlanName_TX, String PlanContent_TX, String PlanStart_DT, String PlanEnd_DT, int AddPost_ID, String Add_DT, String AddUserName_TX, String Edit_DT, String EditUserName_TX) {
        this.JXPlan_ID = JXPlan_ID;
        this.JXPlan_CD = JXPlan_CD;
        this.Area_ID = Area_ID;
        this.Spec_ID = Spec_ID;
        this.ZYX_ID = ZYX_ID;
        this.JXType_ID = JXType_ID;
        this.PlanName_TX = PlanName_TX;
        this.PlanContent_TX = PlanContent_TX;
        this.PlanStart_DT = PlanStart_DT;
        this.PlanEnd_DT = PlanEnd_DT;
        this.AddPost_ID = AddPost_ID;
        this.Add_DT = Add_DT;
        this.AddUserName_TX = AddUserName_TX;
        this.Edit_DT = Edit_DT;
        this.EditUserName_TX = EditUserName_TX;
    }

    public int getJXPlan_ID() {
        return JXPlan_ID;
    }

    public void setJXPlan_ID(int JXPlan_ID) {
        this.JXPlan_ID = JXPlan_ID;
    }

    /** Not-null value. */
    public String getJXPlan_CD() {
        return JXPlan_CD;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setJXPlan_CD(String JXPlan_CD) {
        this.JXPlan_CD = JXPlan_CD;
    }

    public Integer getArea_ID() {
        return Area_ID;
    }

    public void setArea_ID(Integer Area_ID) {
        this.Area_ID = Area_ID;
    }

    public Integer getSpec_ID() {
        return Spec_ID;
    }

    public void setSpec_ID(Integer Spec_ID) {
        this.Spec_ID = Spec_ID;
    }

    public int getZYX_ID() {
        return ZYX_ID;
    }

    public void setZYX_ID(int ZYX_ID) {
        this.ZYX_ID = ZYX_ID;
    }

    public int getJXType_ID() {
        return JXType_ID;
    }

    public void setJXType_ID(int JXType_ID) {
        this.JXType_ID = JXType_ID;
    }

    /** Not-null value. */
    public String getPlanName_TX() {
        return PlanName_TX;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlanName_TX(String PlanName_TX) {
        this.PlanName_TX = PlanName_TX;
    }

    /** Not-null value. */
    public String getPlanContent_TX() {
        return PlanContent_TX;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlanContent_TX(String PlanContent_TX) {
        this.PlanContent_TX = PlanContent_TX;
    }

    /** Not-null value. */
    public String getPlanStart_DT() {
        return PlanStart_DT;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlanStart_DT(String PlanStart_DT) {
        this.PlanStart_DT = PlanStart_DT;
    }

    /** Not-null value. */
    public String getPlanEnd_DT() {
        return PlanEnd_DT;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPlanEnd_DT(String PlanEnd_DT) {
        this.PlanEnd_DT = PlanEnd_DT;
    }

    public int getAddPost_ID() {
        return AddPost_ID;
    }

    public void setAddPost_ID(int AddPost_ID) {
        this.AddPost_ID = AddPost_ID;
    }

    /** Not-null value. */
    public String getAdd_DT() {
        return Add_DT;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAdd_DT(String Add_DT) {
        this.Add_DT = Add_DT;
    }

    /** Not-null value. */
    public String getAddUserName_TX() {
        return AddUserName_TX;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddUserName_TX(String AddUserName_TX) {
        this.AddUserName_TX = AddUserName_TX;
    }

    public String getEdit_DT() {
        return Edit_DT;
    }

    public void setEdit_DT(String Edit_DT) {
        this.Edit_DT = Edit_DT;
    }

    public String getEditUserName_TX() {
        return EditUserName_TX;
    }

    public void setEditUserName_TX(String EditUserName_TX) {
        this.EditUserName_TX = EditUserName_TX;
    }
    
    public boolean getisPlanFinished() {
        return isFinished;
    }

    public void setisPlanFinished(Boolean isFinish) {
        this.isFinished = isFinish;
    }
    @Override
	public String getSearchCondition() {
		 StringBuilder searchStr = new StringBuilder();
	        searchStr.append(JXPlan_CD);
	        searchStr.append(PlanName_TX);
	        searchStr.append(PlanContent_TX);
	        return searchStr.toString();
	}
}
