package com.moons.xst.track.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CYCLE_BY_IDPOS.
 */
public class CycleByIDPos {

    /** Not-null value. */
    private String IDPos_ID;
    /** Not-null value. */
    private String Cycle_ID;

    public CycleByIDPos() {
    }

    public CycleByIDPos(String IDPos_ID, String Cycle_ID) {
        this.IDPos_ID = IDPos_ID;
        this.Cycle_ID = Cycle_ID;
    }

    /** Not-null value. */
    public String getIDPos_ID() {
        return IDPos_ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIDPos_ID(String IDPos_ID) {
        this.IDPos_ID = IDPos_ID;
    }

    /** Not-null value. */
    public String getCycle_ID() {
        return Cycle_ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCycle_ID(String Cycle_ID) {
        this.Cycle_ID = Cycle_ID;
    }

}
