package com.moons.xst.track.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Z__DJ__CYCLE_DTL.
 */
public class Z_DJ_CycleDTL {

    /** Not-null value. */
    private String Cycle_ID;
    private int CycSort_NR;
    /** Not-null value. */
    private String CycStart_TX;
    private int SpanValue_NR;
    /** Not-null value. */
    private String SpanType_CD;
    /** Not-null value. */
    private String TimeMode_CD;
    private int CycTime_NR;
    private String StartTimeList_TX;
    private String EndTimeList_TX;
    private String ShiftList_TX;
    private String OverDayList_TX;
    private String OtherList_TX;
    private String MObjectState_TX;

    public Z_DJ_CycleDTL() {
    }

    public Z_DJ_CycleDTL(String Cycle_ID, int CycSort_NR, String CycStart_TX, int SpanValue_NR, String SpanType_CD, String TimeMode_CD, int CycTime_NR, String StartTimeList_TX, String EndTimeList_TX, String ShiftList_TX, String OverDayList_TX, String OtherList_TX, String MObjectState_TX) {
        this.Cycle_ID = Cycle_ID;
        this.CycSort_NR = CycSort_NR;
        this.CycStart_TX = CycStart_TX;
        this.SpanValue_NR = SpanValue_NR;
        this.SpanType_CD = SpanType_CD;
        this.TimeMode_CD = TimeMode_CD;
        this.CycTime_NR = CycTime_NR;
        this.StartTimeList_TX = StartTimeList_TX;
        this.EndTimeList_TX = EndTimeList_TX;
        this.ShiftList_TX = ShiftList_TX;
        this.OverDayList_TX = OverDayList_TX;
        this.OtherList_TX = OtherList_TX;
        this.MObjectState_TX = MObjectState_TX;
    }

    /** Not-null value. */
    public String getCycle_ID() {
        return Cycle_ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCycle_ID(String Cycle_ID) {
        this.Cycle_ID = Cycle_ID;
    }

    public int getCycSort_NR() {
        return CycSort_NR;
    }

    public void setCycSort_NR(int CycSort_NR) {
        this.CycSort_NR = CycSort_NR;
    }

    /** Not-null value. */
    public String getCycStart_TX() {
        return CycStart_TX;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCycStart_TX(String CycStart_TX) {
        this.CycStart_TX = CycStart_TX;
    }

    public int getSpanValue_NR() {
        return SpanValue_NR;
    }

    public void setSpanValue_NR(int SpanValue_NR) {
        this.SpanValue_NR = SpanValue_NR;
    }

    /** Not-null value. */
    public String getSpanType_CD() {
        return SpanType_CD;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSpanType_CD(String SpanType_CD) {
        this.SpanType_CD = SpanType_CD;
    }

    /** Not-null value. */
    public String getTimeMode_CD() {
        return TimeMode_CD;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTimeMode_CD(String TimeMode_CD) {
        this.TimeMode_CD = TimeMode_CD;
    }

    public int getCycTime_NR() {
        return CycTime_NR;
    }

    public void setCycTime_NR(int CycTime_NR) {
        this.CycTime_NR = CycTime_NR;
    }

    public String getStartTimeList_TX() {
        return StartTimeList_TX;
    }

    public void setStartTimeList_TX(String StartTimeList_TX) {
        this.StartTimeList_TX = StartTimeList_TX;
    }

    public String getEndTimeList_TX() {
        return EndTimeList_TX;
    }

    public void setEndTimeList_TX(String EndTimeList_TX) {
        this.EndTimeList_TX = EndTimeList_TX;
    }

    public String getShiftList_TX() {
        return ShiftList_TX;
    }

    public void setShiftList_TX(String ShiftList_TX) {
        this.ShiftList_TX = ShiftList_TX;
    }

    public String getOverDayList_TX() {
        return OverDayList_TX;
    }

    public void setOverDayList_TX(String OverDayList_TX) {
        this.OverDayList_TX = OverDayList_TX;
    }

    public String getOtherList_TX() {
        return OtherList_TX;
    }

    public void setOtherList_TX(String OtherList_TX) {
        this.OtherList_TX = OtherList_TX;
    }

    public String getMObjectState_TX() {
        return MObjectState_TX;
    }

    public void setMObjectState_TX(String MObjectState_TX) {
        this.MObjectState_TX = MObjectState_TX;
    }

}
