package com.moons.xst.track.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SRLINE_TREE_BY_IDPOS.
 */
public class SRLineTreeByIDPos {

    /** Not-null value. */
    private String IDPos_ID;
    /** Not-null value. */
    private String SRControlPoint_ID;
    private int Name_TX;
    private String TransInfo_TX;

    public SRLineTreeByIDPos() {
    }

    public SRLineTreeByIDPos(String IDPos_ID, String SRControlPoint_ID, int Name_TX, String TransInfo_TX) {
        this.IDPos_ID = IDPos_ID;
        this.SRControlPoint_ID = SRControlPoint_ID;
        this.Name_TX = Name_TX;
        this.TransInfo_TX = TransInfo_TX;
    }

    /** Not-null value. */
    public String getIDPos_ID() {
        return IDPos_ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIDPos_ID(String IDPos_ID) {
        this.IDPos_ID = IDPos_ID;
    }

    /** Not-null value. */
    public String getSRControlPoint_ID() {
        return SRControlPoint_ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSRControlPoint_ID(String SRControlPoint_ID) {
        this.SRControlPoint_ID = SRControlPoint_ID;
    }

    public int getName_TX() {
        return Name_TX;
    }

    public void setName_TX(int Name_TX) {
        this.Name_TX = Name_TX;
    }

    public String getTransInfo_TX() {
        return TransInfo_TX;
    }

    public void setTransInfo_TX(String TransInfo_TX) {
        this.TransInfo_TX = TransInfo_TX;
    }

}
