package com.moons.xst.track.bean;

import java.io.Serializable;

import com.moons.xst.track.common.StringUtils;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Z__DJ__PLAN.
 */
public class Z_DJ_Plan implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3363046744478390173L;
	/** Not-null value. */
	private String DJ_Plan_ID;
	/** Not-null value. */
	private String PlanDesc_TX;
	private int SortNo_NR;
	private String ESTStandard_TX;
	private String DataType_CD;
	private String ZhenDong_Type;
	private String ZhenDong_PP;
	private Integer Cycle_ID;
	private String CycleBaseDate_DT;
	private String IDPos_ID;
	private int CheckMethod;
	private Integer AlarmType_ID;
	private String LowerLimit1_TX;
	private String LowerLimit2_TX;
	private String LowerLimit3_TX;
	private String LowerLimit4_TX;
	private String UpperLimit1_TX;
	private String UpperLimit2_TX;
	private String UpperLimit3_TX;
	private String UpperLimit4_TX;
	private String MetricUnit_TX;
	private String StandardValue_TX;
	private String ParmLowerLimit_TX;
	private String ParmUpperLimit_TX;
	private Integer DataCodeGroup_ID;
	/** Not-null value. */
	private String MustCheck_YN;
	private String SpecCase_YN;
	private String SpecCase_TX;
	private Float WenDu_FSL;
	private String DisStart_TM;
	private String DisEnd_TM;
	private String LKPoint_ID;
	private String SRPoint_ID;
	private String MObjectState_TX;
	private String DefaultResult_TX;
	private Integer MobjectBugSpec_ID;
	private String SensorRatio_TX;
	private String LastResult_TX;
	private Float WARNINGVALUE_NR;
	private String LastComplete_DT;
	private String TransInfo_TX;
	private String ConLevel_TX;
	private String PlanCycleIDsStr_TX;
	private String GroupNum_NR;
	private Integer MaxFreq_NR;
	private Integer FFTLine_NR;
	private Integer WindowType_NR;
	private Integer AverNum_NR;
	private String Speed_YN;
	private Integer AverageType_NR;
	private Integer Overlap_NR;
	//差值报警比较字段，存入的就是上次结果
	private String LastResultForDifferent_TX;
	
	private String LastSRResult_TM;	
	private String LastSRResult_TX;

	public Z_DJ_Plan() {
	}

	public Z_DJ_Plan(String DJ_Plan_ID, String PlanDesc_TX, int SortNo_NR,
			String ESTStandard_TX, String DataType_CD, String ZhenDong_Type,
			String ZhenDong_PP, Integer Cycle_ID, String CycleBaseDate_DT,
			String IDPos_ID, int CheckMethod, Integer AlarmType_ID,
			String LowerLimit1_TX, String LowerLimit2_TX,
			String LowerLimit3_TX, String LowerLimit4_TX,
			String UpperLimit1_TX, String UpperLimit2_TX,
			String UpperLimit3_TX, String UpperLimit4_TX, String MetricUnit_TX,
			String StandardValue_TX, String ParmLowerLimit_TX,
			String ParmUpperLimit_TX, Integer DataCodeGroup_ID,
			String MustCheck_YN, String SpecCase_YN, String SpecCase_TX,
			Float WenDu_FSL, String DisStart_TM, String DisEnd_TM,
			String LKPoint_ID, String SRPoint_ID, String MObjectState_TX,
			String DefaultResult_TX, Integer MobjectBugSpec_ID,
			String SensorRatio_TX, String LastResult_TX, Float WARNINGVALUE_NR,
			String LastComplete_DT, String TransInfo_TX, String ConLevel_TX,
			String PlanCycleIDsStr_TX, String GroupNum_NR, Integer MaxFreq_NR,
			Integer FFTLine_NR, Integer WindowType_NR, Integer AverNum_NR,
			String Speed_YN, Integer AverageType_NR, Integer Overlap_NR) {
		this.DJ_Plan_ID = DJ_Plan_ID;
		this.PlanDesc_TX = PlanDesc_TX;
		this.SortNo_NR = SortNo_NR;
		this.ESTStandard_TX = ESTStandard_TX;
		this.DataType_CD = DataType_CD;
		this.ZhenDong_Type = ZhenDong_Type;
		this.ZhenDong_PP = ZhenDong_PP;
		this.Cycle_ID = Cycle_ID;
		this.CycleBaseDate_DT = CycleBaseDate_DT;
		this.IDPos_ID = IDPos_ID;
		this.CheckMethod = CheckMethod;
		this.AlarmType_ID = AlarmType_ID;
		this.LowerLimit1_TX = LowerLimit1_TX;
		this.LowerLimit2_TX = LowerLimit2_TX;
		this.LowerLimit3_TX = LowerLimit3_TX;
		this.LowerLimit4_TX = LowerLimit4_TX;
		this.UpperLimit1_TX = UpperLimit1_TX;
		this.UpperLimit2_TX = UpperLimit2_TX;
		this.UpperLimit3_TX = UpperLimit3_TX;
		this.UpperLimit4_TX = UpperLimit4_TX;
		this.MetricUnit_TX = MetricUnit_TX;
		this.StandardValue_TX = StandardValue_TX;
		this.ParmLowerLimit_TX = ParmLowerLimit_TX;
		this.ParmUpperLimit_TX = ParmUpperLimit_TX;
		this.DataCodeGroup_ID = DataCodeGroup_ID;
		this.MustCheck_YN = MustCheck_YN;
		this.SpecCase_YN = SpecCase_YN;
		this.SpecCase_TX = SpecCase_TX;
		this.WenDu_FSL = WenDu_FSL;
		this.DisStart_TM = DisStart_TM;
		this.DisEnd_TM = DisEnd_TM;
		this.LKPoint_ID = LKPoint_ID;
		this.SRPoint_ID = SRPoint_ID;
		this.MObjectState_TX = MObjectState_TX;
		this.DefaultResult_TX = DefaultResult_TX;
		this.MobjectBugSpec_ID = MobjectBugSpec_ID;
		this.SensorRatio_TX = SensorRatio_TX;
		this.LastResult_TX = LastResult_TX;
		this.WARNINGVALUE_NR = WARNINGVALUE_NR;
		this.LastComplete_DT = LastComplete_DT;
		this.TransInfo_TX = TransInfo_TX;
		this.ConLevel_TX = ConLevel_TX;
		this.PlanCycleIDsStr_TX = PlanCycleIDsStr_TX;
		this.GroupNum_NR = GroupNum_NR;
		this.MaxFreq_NR = MaxFreq_NR;
		this.FFTLine_NR = FFTLine_NR;
		this.WindowType_NR = WindowType_NR;
		this.AverNum_NR = AverNum_NR;
		this.Speed_YN = Speed_YN;
		this.AverageType_NR = AverageType_NR;
		this.Overlap_NR = Overlap_NR;
		
		this.LastResultForDifferent_TX = LastResult_TX;
		
		this.LastSRResult_TM = "";
		this.LastSRResult_TX = "";
	}

	/** Not-null value. */
	public String getDJ_Plan_ID() {
		return DJ_Plan_ID;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setDJ_Plan_ID(String DJ_Plan_ID) {
		this.DJ_Plan_ID = DJ_Plan_ID;
	}

	/** Not-null value. */
	public String getPlanDesc_TX() {
		return PlanDesc_TX;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setPlanDesc_TX(String PlanDesc_TX) {
		this.PlanDesc_TX = PlanDesc_TX;
	}

	public int getSortNo_NR() {
		return SortNo_NR;
	}

	public void setSortNo_NR(int SortNo_NR) {
		this.SortNo_NR = SortNo_NR;
	}

	public String getESTStandard_TX() {
		return ESTStandard_TX;
	}

	public void setESTStandard_TX(String ESTStandard_TX) {
		this.ESTStandard_TX = ESTStandard_TX;
	}

	public String getDataType_CD() {
		return DataType_CD;
	}

	public void setDataType_CD(String DataType_CD) {
		this.DataType_CD = DataType_CD;
	}

	public String getZhenDong_Type() {
		return ZhenDong_Type;
	}

	public void setZhenDong_Type(String ZhenDong_Type) {
		this.ZhenDong_Type = ZhenDong_Type;
	}

	public String getZhenDong_PP() {
		return ZhenDong_PP;
	}

	public void setZhenDong_PP(String ZhenDong_PP) {
		this.ZhenDong_PP = ZhenDong_PP;
	}

	public Integer getCycle_ID() {
		return Cycle_ID;
	}

	public void setCycle_ID(Integer Cycle_ID) {
		this.Cycle_ID = Cycle_ID;
	}

	public String getCycleBaseDate_DT() {
		return CycleBaseDate_DT;
	}

	public void setCycleBaseDate_DT(String CycleBaseDate_DT) {
		this.CycleBaseDate_DT = CycleBaseDate_DT;
	}

	public String getIDPos_ID() {
		return IDPos_ID;
	}

	public void setIDPos_ID(String IDPos_ID) {
		this.IDPos_ID = IDPos_ID;
	}

	public int getCheckMethod() {
		return CheckMethod;
	}

	public void setCheckMethod(int CheckMethod) {
		this.CheckMethod = CheckMethod;
	}

	public Integer getAlarmType_ID() {
		return AlarmType_ID;
	}

	public void setAlarmType_ID(Integer AlarmType_ID) {
		this.AlarmType_ID = AlarmType_ID;
	}

	public String getLowerLimit1_TX() {
		return LowerLimit1_TX;
	}

	public void setLowerLimit1_TX(String LowerLimit1_TX) {
		this.LowerLimit1_TX = LowerLimit1_TX;
	}

	public String getLowerLimit2_TX() {
		return LowerLimit2_TX;
	}

	public void setLowerLimit2_TX(String LowerLimit2_TX) {
		this.LowerLimit2_TX = LowerLimit2_TX;
	}

	public String getLowerLimit3_TX() {
		return LowerLimit3_TX;
	}

	public void setLowerLimit3_TX(String LowerLimit3_TX) {
		this.LowerLimit3_TX = LowerLimit3_TX;
	}

	public String getLowerLimit4_TX() {
		return LowerLimit4_TX;
	}

	public void setLowerLimit4_TX(String LowerLimit4_TX) {
		this.LowerLimit4_TX = LowerLimit4_TX;
	}

	public String getUpperLimit1_TX() {
		return UpperLimit1_TX;
	}

	public void setUpperLimit1_TX(String UpperLimit1_TX) {
		this.UpperLimit1_TX = UpperLimit1_TX;
	}

	public String getUpperLimit2_TX() {
		return UpperLimit2_TX;
	}

	public void setUpperLimit2_TX(String UpperLimit2_TX) {
		this.UpperLimit2_TX = UpperLimit2_TX;
	}

	public String getUpperLimit3_TX() {
		return UpperLimit3_TX;
	}

	public void setUpperLimit3_TX(String UpperLimit3_TX) {
		this.UpperLimit3_TX = UpperLimit3_TX;
	}

	public String getUpperLimit4_TX() {
		return UpperLimit4_TX;
	}

	public void setUpperLimit4_TX(String UpperLimit4_TX) {
		this.UpperLimit4_TX = UpperLimit4_TX;
	}

	public String getMetricUnit_TX() {
		return MetricUnit_TX;
	}

	public void setMetricUnit_TX(String MetricUnit_TX) {
		this.MetricUnit_TX = MetricUnit_TX;
	}

	public String getStandardValue_TX() {
		return StandardValue_TX;
	}

	public void setStandardValue_TX(String StandardValue_TX) {
		this.StandardValue_TX = StandardValue_TX;
	}

	public String getParmLowerLimit_TX() {
		return ParmLowerLimit_TX;
	}

	public void setParmLowerLimit_TX(String ParmLowerLimit_TX) {
		this.ParmLowerLimit_TX = ParmLowerLimit_TX;
	}

	public String getParmUpperLimit_TX() {
		return ParmUpperLimit_TX;
	}

	public void setParmUpperLimit_TX(String ParmUpperLimit_TX) {
		this.ParmUpperLimit_TX = ParmUpperLimit_TX;
	}

	public Integer getDataCodeGroup_ID() {
		return DataCodeGroup_ID;
	}

	public void setDataCodeGroup_ID(Integer DataCodeGroup_ID) {
		this.DataCodeGroup_ID = DataCodeGroup_ID;
	}

	/** Not-null value. */
	public String getMustCheck_YN() {
		return MustCheck_YN;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setMustCheck_YN(String MustCheck_YN) {
		this.MustCheck_YN = MustCheck_YN;
	}

	public String getSpecCase_YN() {
		return SpecCase_YN;
	}

	public void setSpecCase_YN(String SpecCase_YN) {
		this.SpecCase_YN = SpecCase_YN;
	}

	public String getSpecCase_TX() {
		return SpecCase_TX;
	}

	public void setSpecCase_TX(String SpecCase_TX) {
		this.SpecCase_TX = SpecCase_TX;
	}

	public Float getWenDu_FSL() {
		return WenDu_FSL;
	}

	public void setWenDu_FSL(Float WenDu_FSL) {
		this.WenDu_FSL = WenDu_FSL;
	}

	public String getDisStart_TM() {
		return DisStart_TM;
	}

	public void setDisStart_TM(String DisStart_TM) {
		this.DisStart_TM = DisStart_TM;
	}

	public String getDisEnd_TM() {
		return DisEnd_TM;
	}

	public void setDisEnd_TM(String DisEnd_TM) {
		this.DisEnd_TM = DisEnd_TM;
	}

	public String getLKPoint_ID() {
		return LKPoint_ID;
	}

	public void setLKPoint_ID(String LKPoint_ID) {
		this.LKPoint_ID = LKPoint_ID;
	}

	public String getSRPoint_ID() {
		return SRPoint_ID;
	}

	public void setSRPoint_ID(String SRPoint_ID) {
		this.SRPoint_ID = SRPoint_ID;
	}

	public String getMObjectState_TX() {
		return MObjectState_TX;
	}

	public void setMObjectState_TX(String MObjectState_TX) {
		this.MObjectState_TX = MObjectState_TX;
	}

	public String getDefaultResult_TX() {
		return DefaultResult_TX;
	}

	public void setDefaultResult_TX(String DefaultResult_TX) {
		this.DefaultResult_TX = DefaultResult_TX;
	}

	public Integer getMobjectBugSpec_ID() {
		return MobjectBugSpec_ID;
	}

	public void setMobjectBugSpec_ID(Integer MobjectBugSpec_ID) {
		this.MobjectBugSpec_ID = MobjectBugSpec_ID;
	}

	public String getSensorRatio_TX() {
		return SensorRatio_TX;
	}

	public void setSensorRatio_TX(String SensorRatio_TX) {
		this.SensorRatio_TX = SensorRatio_TX;
	}

	public String getLastResult_TX() {
		return LastResult_TX;
	}

	public void setLastResult_TX(String LastResult_TX) {
		this.LastResult_TX = LastResult_TX;
	}

	public Float getWARNINGVALUE_NR() {
		return WARNINGVALUE_NR;
	}

	public void setWARNINGVALUE_NR(Float WARNINGVALUE_NR) {
		this.WARNINGVALUE_NR = WARNINGVALUE_NR;
	}

	public String getLastComplete_DT() {
		return LastComplete_DT;
	}

	public void setLastComplete_DT(String LastComplete_DT) {
		this.LastComplete_DT = LastComplete_DT;
	}

	public String getTransInfo_TX() {
		return TransInfo_TX;
	}

	public void setTransInfo_TX(String TransInfo_TX) {
		this.TransInfo_TX = TransInfo_TX;
	}

	public String getConLevel_TX() {
		return ConLevel_TX;
	}

	public void setConLevel_TX(String ConLevel_TX) {
		this.ConLevel_TX = ConLevel_TX;
	}

	public String getPlanCycleIDsStr_TX() {
		return PlanCycleIDsStr_TX;
	}

	public void setPlanCycleIDsStr_TX(String PlanCycleIDsStr_TX) {
		this.PlanCycleIDsStr_TX = PlanCycleIDsStr_TX;
	}

	public String getGroupNum_NR() {
		return GroupNum_NR;
	}

	public void setGroupNum_NR(String GroupNum_NR) {
		this.GroupNum_NR = GroupNum_NR;
	}

	public Integer getMaxFreq_NR() {
		return MaxFreq_NR;
	}

	public void setMaxFreq_NR(Integer MaxFreq_NR) {
		this.MaxFreq_NR = MaxFreq_NR;
	}

	public Integer getFFTLine_NR() {
		return FFTLine_NR;
	}

	public void setFFTLine_NR(Integer FFTLine_NR) {
		this.FFTLine_NR = FFTLine_NR;
	}

	public Integer getWindowType_NR() {
		return WindowType_NR;
	}

	public void setWindowType_NR(Integer WindowType_NR) {
		this.WindowType_NR = WindowType_NR;
	}

	public Integer getAverNum_NR() {
		return AverNum_NR;
	}

	public void setAverNum_NR(Integer AverNum_NR) {
		this.AverNum_NR = AverNum_NR;
	}

	public String getSpeed_YN() {
		return Speed_YN;
	}

	public void setSpeed_YN(String Speed_YN) {
		this.Speed_YN = Speed_YN;
	}

	public Integer getAverageType_NR() {
		return AverageType_NR;
	}

	public void setAverageType_NR(Integer AverageType_NR) {
		this.AverageType_NR = AverageType_NR;
	}

	public Integer getOverlap_NR() {
		return Overlap_NR;
	}

	public void setOverlap_NR(Integer Overlap_NR) {
		this.Overlap_NR = Overlap_NR;
	}
	
	public void setLastResultForDifferent_TX(String result){
		LastResultForDifferent_TX = result;
	}
	
	public String getLastResultForDifferent_TX() {
		return LastResultForDifferent_TX;
	}
	
	public String getLastSRResult_TM() {
		return LastSRResult_TM;
	}
	public void setLastSRResult_TM(String s) {
		LastSRResult_TM = s;
	}
	
	public String getLastSRResult_TX() {
		return LastSRResult_TX;
	}
	public void setLastSRResult_TX(String s) {
		LastSRResult_TX = s;
	}

	/**
	 * 测试用
	 * 
	 * @return
	 */
	public Boolean gettempMark() {
		if (StringUtils.isEmpty(LastComplete_DT))
			return false;
		else
			return true;
	}

	public void buildObject(String PlanID, String PlanDesc, String LastTime,
			String LastResult, String PlanUnit, String DataCode,
			String Cycle_ID, String CycleBaseDate_DT, String IDPos_ID) {
		// DJLine oneDJLine = null;
		// oneDJLine = new DJLine();
		this.setDJ_Plan_ID(PlanID);
		this.setPlanDesc_TX(PlanDesc);
		this.setLastComplete_DT(LastTime);
		this.setLastResult_TX(LastResult);
		this.setMetricUnit_TX(PlanUnit);
		this.setDataType_CD(DataCode);
		this.Cycle_ID = Integer.parseInt(Cycle_ID);
		this.CycleBaseDate_DT = CycleBaseDate_DT;
		this.IDPos_ID = IDPos_ID;
		// return oneDJLine;

	}
}
