package com.moons.xst.track.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table Z__RELATION.
 */
public class Z_Relation {

    /** Not-null value. */
    private String Int_ID;
    /** Not-null value. */
    private String String_ID;
    /** Not-null value. */
    private String RelationType;
    private String Expand_TX;

    public Z_Relation() {
    }

    public Z_Relation(String Int_ID, String String_ID, String RelationType, String Expand_TX) {
        this.Int_ID = Int_ID;
        this.String_ID = String_ID;
        this.RelationType = RelationType;
        this.Expand_TX = Expand_TX;
    }

    /** Not-null value. */
    public String getInt_ID() {
        return Int_ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setInt_ID(String Int_ID) {
        this.Int_ID = Int_ID;
    }

    /** Not-null value. */
    public String getString_ID() {
        return String_ID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setString_ID(String String_ID) {
        this.String_ID = String_ID;
    }

    /** Not-null value. */
    public String getRelationType() {
        return RelationType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRelationType(String RelationType) {
        this.RelationType = RelationType;
    }

    public String getExpand_TX() {
        return Expand_TX;
    }

    public void setExpand_TX(String Expand_TX) {
        this.Expand_TX = Expand_TX;
    }

}
