package com.moons.xst.track.dao;

import java.util.List;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.moons.xst.sqlite.DJDAOSession;
import com.moons.xst.track.bean.DJ_ControlPoint;
import com.moons.xst.track.bean.Z_MObjectState;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table Z_MOBJECT_STATE.
*/
public class Z_MObjectStateDao extends AbstractDao<Z_MObjectState, Void> {

    public static final String TABLENAME = "Z_MOBJECTSTATE";

    /**
     * Properties of entity Z_MObjectState.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property State_ID = new Property(0, String.class, "State_ID", false, "STATE_ID");
        public final static Property Name_TX = new Property(1, String.class, "Name_TX", false, "NAME_TX");
    };


    public Z_MObjectStateDao(DaoConfig config) {
        super(config);
    }
    
    public Z_MObjectStateDao(DaoConfig config, DJDAOSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'Z_MOBJECT_STATE' (" + //
                "'STATE_ID' TEXT NOT NULL ," + // 0: State_ID
                "'NAME_TX' TEXT NOT NULL );"); // 1: Name_TX
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'Z_MOBJECT_STATE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Z_MObjectState entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getState_ID());
        stmt.bindString(2, entity.getName_TX());
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public Z_MObjectState readEntity(Cursor cursor, int offset) {
        Z_MObjectState entity = new Z_MObjectState( //
            cursor.getString(offset + 0), // State_ID
            cursor.getString(offset + 1) // Name_TX
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Z_MObjectState entity, int offset) {
        entity.setState_ID(cursor.getString(offset + 0));
        entity.setName_TX(cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(Z_MObjectState entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(Z_MObjectState entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    public List<Z_MObjectState> load() {
		String sqlString = "select * from Z_MobjectState Order By State_ID asc";
		return loadAllAndCloseCursor(db.rawQuery(sqlString, null));
	}
}
