package com.moons.xst.track.bean;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WORK__DETAIL__BILL.
 */
public class Work_Detail_Bill implements Serializable {

	private String Work_Bill_Item_ID;
	private Integer Work_Bill_ID;
	private String Work_Bill_Item_DataType_CD;
	private String Work_Bill_Item_ItemTitleA;
	private String Work_Bill_Item_ItemTitleB;
	private String Work_Bill_Item_AQCS1_TX;
	private String Work_Bill_Item_AQCS2_TX;
	private String Work_Bill_Item_AQCS3_TX;
	private String Work_Bill_Item_AQCS4_TX;
	private String Work_Bill_Item_Exe_Time;
	private Integer Work_Bill_Item_Order;
	private String Work_Bill_Item_State;
	private Integer Work_Bill_Item_UCSettingID;

	public Work_Detail_Bill() {
	}

	public Work_Detail_Bill(String Work_Bill_Item_ID) {
		this.Work_Bill_Item_ID = Work_Bill_Item_ID;
	}

	public Work_Detail_Bill(String work_Bill_Item_ID, Integer work_Bill_ID,
			String work_Bill_Item_DataType_CD,
			String work_Bill_Item_ItemTitleA, String work_Bill_Item_ItemTitleB,
			String work_Bill_Item_AQCS1_TX, String work_Bill_Item_AQCS2_TX,
			String work_Bill_Item_AQCS3_TX, String work_Bill_Item_AQCS4_TX,
			String work_Bill_Item_Exe_Time, Integer work_Bill_Item_Order,
			String work_Bill_Item_State, Integer work_Bill_Item_UCSettingID) {
		Work_Bill_Item_ID = work_Bill_Item_ID;
		Work_Bill_ID = work_Bill_ID;
		Work_Bill_Item_DataType_CD = work_Bill_Item_DataType_CD;
		Work_Bill_Item_ItemTitleA = work_Bill_Item_ItemTitleA;
		Work_Bill_Item_ItemTitleB = work_Bill_Item_ItemTitleB;
		Work_Bill_Item_AQCS1_TX = work_Bill_Item_AQCS1_TX;
		Work_Bill_Item_AQCS2_TX = work_Bill_Item_AQCS2_TX;
		Work_Bill_Item_AQCS3_TX = work_Bill_Item_AQCS3_TX;
		Work_Bill_Item_AQCS4_TX = work_Bill_Item_AQCS4_TX;
		Work_Bill_Item_Exe_Time = work_Bill_Item_Exe_Time;
		Work_Bill_Item_Order = work_Bill_Item_Order;
		Work_Bill_Item_State = work_Bill_Item_State;
		Work_Bill_Item_UCSettingID = work_Bill_Item_UCSettingID;
	}

	public Integer getWork_Bill_Item_UCSettingID() {
		return Work_Bill_Item_UCSettingID;
	}

	public void setWork_Bill_Item_UCSettingID(Integer work_Bill_Item_UCSettingID) {
		Work_Bill_Item_UCSettingID = work_Bill_Item_UCSettingID;
	}

	public String getWork_Bill_Item_ItemTitleA() {
		return Work_Bill_Item_ItemTitleA;
	}

	public void setWork_Bill_Item_ItemTitleA(String work_Bill_Item_ItemTitleA) {
		Work_Bill_Item_ItemTitleA = work_Bill_Item_ItemTitleA;
	}

	public String getWork_Bill_Item_ItemTitleB() {
		return Work_Bill_Item_ItemTitleB;
	}

	public void setWork_Bill_Item_ItemTitleB(String work_Bill_Item_ItemTitleB) {
		Work_Bill_Item_ItemTitleB = work_Bill_Item_ItemTitleB;
	}

	public String getWork_Bill_Item_ID() {
		return Work_Bill_Item_ID;
	}

	public void setWork_Bill_Item_ID(String Work_Bill_Item_ID) {
		this.Work_Bill_Item_ID = Work_Bill_Item_ID;
	}

	public Integer getWork_Bill_ID() {
		return Work_Bill_ID;
	}

	public void setWork_Bill_ID(Integer Work_Bill_ID) {
		this.Work_Bill_ID = Work_Bill_ID;
	}

	public String getWork_Bill_Item_DataType_CD() {
		return Work_Bill_Item_DataType_CD;
	}

	public void setWork_Bill_Item_DataType_CD(String Work_Bill_Item_DataType_CD) {
		this.Work_Bill_Item_DataType_CD = Work_Bill_Item_DataType_CD;
	}

	public String getWork_Bill_Item_AQCS1_TX() {
		return Work_Bill_Item_AQCS1_TX;
	}

	public void setWork_Bill_Item_AQCS1_TX(String Work_Bill_Item_AQCS1_TX) {
		this.Work_Bill_Item_AQCS1_TX = Work_Bill_Item_AQCS1_TX;
	}

	public String getWork_Bill_Item_AQCS2_TX() {
		return Work_Bill_Item_AQCS2_TX;
	}

	public void setWork_Bill_Item_AQCS2_TX(String Work_Bill_Item_AQCS2_TX) {
		this.Work_Bill_Item_AQCS2_TX = Work_Bill_Item_AQCS2_TX;
	}

	public String getWork_Bill_Item_AQCS3_TX() {
		return Work_Bill_Item_AQCS3_TX;
	}

	public void setWork_Bill_Item_AQCS3_TX(String Work_Bill_Item_AQCS3_TX) {
		this.Work_Bill_Item_AQCS3_TX = Work_Bill_Item_AQCS3_TX;
	}

	public String getWork_Bill_Item_AQCS4_TX() {
		return Work_Bill_Item_AQCS4_TX;
	}

	public void setWork_Bill_Item_AQCS4_TX(String Work_Bill_Item_AQCS4_TX) {
		this.Work_Bill_Item_AQCS4_TX = Work_Bill_Item_AQCS4_TX;
	}

	public String getWork_Bill_Item_Exe_Time() {
		return Work_Bill_Item_Exe_Time;
	}

	public void setWork_Bill_Item_Exe_Time(String Work_Bill_Item_Exe_Time) {
		this.Work_Bill_Item_Exe_Time = Work_Bill_Item_Exe_Time;
	}

	public Integer getWork_Bill_Item_Order() {
		return Work_Bill_Item_Order;
	}

	public void setWork_Bill_Item_Order(Integer Work_Bill_Item_Order) {
		this.Work_Bill_Item_Order = Work_Bill_Item_Order;
	}

	public String getWork_Bill_Item_State() {
		return Work_Bill_Item_State;
	}

	public void setWork_Bill_Item_State(String Work_Bill_Item_State) {
		this.Work_Bill_Item_State = Work_Bill_Item_State;
	}

}
