package com.moons.xst.track.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.moons.xst.sqlite.DJDAOSession;
import com.moons.xst.track.bean.CycleBySRLineTree;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CYCLE_BY_SRLINE_TREE.
*/
public class CycleBySRLineTreeDao extends AbstractDao<CycleBySRLineTree, Void> {

    public static final String TABLENAME = "CYCLEBYSRLINETREE";

    /**
     * Properties of entity CycleBySRLineTree.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Cycle_ID = new Property(0, String.class, "Cycle_ID", false, "CYCLE_ID");
        public final static Property SRControlPoint_ID = new Property(1, String.class, "SRControlPoint_ID", false, "SRCONTROLPOINT_ID");
    };


    public CycleBySRLineTreeDao(DaoConfig config) {
        super(config);
    }
    
    public CycleBySRLineTreeDao(DaoConfig config, DJDAOSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CYCLE_BY_SRLINE_TREE' (" + //
                "'CYCLE_ID' TEXT NOT NULL ," + // 0: Cycle_ID
                "'SRCONTROL_POINT_ID' TEXT NOT NULL );"); // 1: SRControlPoint_ID
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CYCLE_BY_SRLINE_TREE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CycleBySRLineTree entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getCycle_ID());
        stmt.bindString(2, entity.getSRControlPoint_ID());
    }

    /** @inheritdoc */
    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    /** @inheritdoc */
    @Override
    public CycleBySRLineTree readEntity(Cursor cursor, int offset) {
        CycleBySRLineTree entity = new CycleBySRLineTree( //
            cursor.getString(offset + 0), // Cycle_ID
            cursor.getString(offset + 1) // SRControlPoint_ID
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CycleBySRLineTree entity, int offset) {
        entity.setCycle_ID(cursor.getString(offset + 0));
        entity.setSRControlPoint_ID(cursor.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected Void updateKeyAfterInsert(CycleBySRLineTree entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    /** @inheritdoc */
    @Override
    public Void getKey(CycleBySRLineTree entity) {
        return null;
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
