package com.moons.xst.track.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DJ__TASK_IDPOS_HIS.
 */
public class DJ_TaskIDPosHis {

	/** Not-null value. */
	private String IDPos_ID;
	/** Not-null value. */
	private String IDPosStart_TM;
	private String IDPosEnd_TM;
	private String Query_DT;
	/** Not-null value. */
	private String AppUser_CD;
	private String AppUserName_TX;
	private String ShiftName_TX;
	private String ShiftGroupName_TX;
	private Integer TimeCount_NR;
	private String TransInfo_TX;
	private String GPSInfo_TX;

	public DJ_TaskIDPosHis() {
	}

	public DJ_TaskIDPosHis(String IDPos_ID, String IDPosStart_TM,
			String IDPosEnd_TM, String Query_DT, String AppUser_CD,
			String AppUserName_TX, String ShiftName_TX,
			String ShiftGroupName_TX, Integer TimeCount_NR,
			String TransInfo_TX, String GPSInfo_TX) {
		this.IDPos_ID = IDPos_ID;
		this.IDPosStart_TM = IDPosStart_TM;
		this.IDPosEnd_TM = IDPosEnd_TM;
		this.Query_DT = Query_DT;
		this.AppUser_CD = AppUser_CD;
		this.AppUserName_TX = AppUserName_TX;
		this.ShiftName_TX = ShiftName_TX;
		this.ShiftGroupName_TX = ShiftGroupName_TX;
		this.TimeCount_NR = TimeCount_NR;
		this.TransInfo_TX = TransInfo_TX;
		this.GPSInfo_TX = GPSInfo_TX;
	}

	/** Not-null value. */
	public String getIDPos_ID() {
		return IDPos_ID;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setIDPos_ID(String IDPos_ID) {
		this.IDPos_ID = IDPos_ID;
	}

	/** Not-null value. */
	public String getIDPosStart_TM() {
		return IDPosStart_TM;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setIDPosStart_TM(String IDPosStart_TM) {
		this.IDPosStart_TM = IDPosStart_TM;
	}

	public String getIDPosEnd_TM() {
		return IDPosEnd_TM;
	}

	public void setIDPosEnd_TM(String IDPosEnd_TM) {
		this.IDPosEnd_TM = IDPosEnd_TM;
	}

	public String getQuery_DT() {
		return Query_DT;
	}

	public void setQuery_DT(String Query_DT) {
		this.Query_DT = Query_DT;
	}

	/** Not-null value. */
	public String getAppUser_CD() {
		return AppUser_CD;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setAppUser_CD(String AppUser_CD) {
		this.AppUser_CD = AppUser_CD;
	}

	public String getAppUserName_TX() {
		return AppUserName_TX;
	}

	public void setAppUserName_TX(String AppUserName_TX) {
		this.AppUserName_TX = AppUserName_TX;
	}

	public String getShiftName_TX() {
		return ShiftName_TX;
	}

	public void setShiftName_TX(String ShiftName_TX) {
		this.ShiftName_TX = ShiftName_TX;
	}

	public String getShiftGroupName_TX() {
		return ShiftGroupName_TX;
	}

	public void setShiftGroupName_TX(String ShiftGroupName_TX) {
		this.ShiftGroupName_TX = ShiftGroupName_TX;
	}

	public Integer getTimeCount_NR() {
		return TimeCount_NR;
	}

	public void setTimeCount_NR(Integer TimeCount_NR) {
		this.TimeCount_NR = TimeCount_NR;
	}

	public String getTransInfo_TX() {
		return TransInfo_TX;
	}

	public void setTransInfo_TX(String TransInfo_TX) {
		this.TransInfo_TX = TransInfo_TX;
	}

	public void setGPSInfo_TX(String gpsInfoTX) {
		this.GPSInfo_TX = gpsInfoTX;
	}

	public String getGPSInfo_TX() {
		return GPSInfo_TX;
	}
}
