package com.moons.xst.sqlite;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import com.moons.xst.track.dao.OverhaulPlanDao;
import com.moons.xst.track.dao.OverhaulProjectDao;
import com.moons.xst.track.dao.OverhaulUserDao;

import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 3): knows all DAOs.
*/
public class OverhaulDaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        OverhaulUserDao.createTable(db, ifNotExists);
        OverhaulPlanDao.createTable(db, ifNotExists);
        OverhaulProjectDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
    	OverhaulUserDao.dropTable(db, ifExists);
    	OverhaulPlanDao.dropTable(db, ifExists);
    	OverhaulProjectDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
           // createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public OverhaulDaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(OverhaulUserDao.class);
        registerDaoClass(OverhaulPlanDao.class);
        registerDaoClass(OverhaulProjectDao.class);
    }
    
    public OverhaulDaoSession newSession() {
        return new OverhaulDaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public OverhaulDaoSession newSession(IdentityScopeType type) {
        return new OverhaulDaoSession(db, type, daoConfigMap);
    }
    
}
