package com.moons.xst.sqlite;

import com.moons.xst.track.dao.ProvisionalMDao;
import com.moons.xst.track.dao.TempMeasureBaseInfoDao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1,000): knows all DAOs.
*/
public class TempMeasureDaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1000;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
    	TempMeasureBaseInfoDao.createTable(db, ifNotExists);
    	ProvisionalMDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
    	TempMeasureBaseInfoDao.dropTable(db, ifExists);
    	ProvisionalMDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public TempMeasureDaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(TempMeasureBaseInfoDao.class);
        registerDaoClass(ProvisionalMDao.class);
    }
    
    @Override
	public TempMeasureDaoSession newSession() {
        return new TempMeasureDaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    @Override
	public TempMeasureDaoSession newSession(IdentityScopeType type) {
        return new TempMeasureDaoSession(db, type, daoConfigMap);
    }
    
}
