package com.moons.xst.sqlite;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import com.moons.xst.track.bean.BillUsers;
import com.moons.xst.track.bean.Work_Bill;
import com.moons.xst.track.bean.Work_Detail_Bill;
import com.moons.xst.track.dao.UsersDao;
import com.moons.xst.track.dao.Work_BillDao;
import com.moons.xst.track.dao.Work_Detail_BillDao;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class WorkResultSession extends AbstractDaoSession {

    private final DaoConfig work_BillDaoConfig;
    private final DaoConfig work_Detail_BillDaoConfig;

    private final Work_BillDao work_BillDao;
    private final Work_Detail_BillDao work_Detail_BillDao;

    public WorkResultSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        work_BillDaoConfig = daoConfigMap.get(Work_BillDao.class).clone();
        work_BillDaoConfig.initIdentityScope(type);

        work_Detail_BillDaoConfig = daoConfigMap.get(Work_Detail_BillDao.class).clone();
        work_Detail_BillDaoConfig.initIdentityScope(type);

        work_BillDao = new Work_BillDao(work_BillDaoConfig, this);
        work_Detail_BillDao = new Work_Detail_BillDao(work_Detail_BillDaoConfig, this);

        registerDao(Work_Bill.class, work_BillDao);
        registerDao(Work_Detail_Bill.class, work_Detail_BillDao);
    }
    
    public void clear() {
        work_BillDaoConfig.getIdentityScope().clear();
        work_Detail_BillDaoConfig.getIdentityScope().clear();
    }

    public Work_BillDao getWork_BillDao() {
        return work_BillDao;
    }

    public Work_Detail_BillDao getWork_Detail_BillDao() {
        return work_Detail_BillDao;
    }

}
