package com.moons.xst.track.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GPSXXPLAN_RESULT.
 */
public class GPSXXPlanResult {

    private Integer XXUncheck_ID;
    private Integer Partition_ID;
    private Integer GpsXXItem_ID;
    private Integer GPSUnCheck_ID;
    private String TaskStart_TM;
    private String TaskEnd_TM;
    private String Query_DT;
    private Integer Round_NR;
    private String ShiftName_TX;
    private String GPSPoint_ID;
    private String ShiftGroupName_TX;
    private Integer Post_ID;
    private String Post_CD;
    private String PostName_TX;
    private Integer Appuser_ID;
    private String AppUser_CD;
    private String AppUserName_TX;
    private String Complete_CD;
    private String Complete_TM;
    private Integer CheckUser_ID;
    private String CheckUser_TX;
    private Integer CheckUserPost_ID;
    private String ISMemo_YN;
    private String Memo_TX;
    private String AuditUserName_TX;
    private String Audit_DT;
    private String XXResult_TX;
    private String XXDesc_TX;

    public GPSXXPlanResult() {
    }

    public GPSXXPlanResult(Integer XXUncheck_ID, Integer Partition_ID, Integer GpsXXItem_ID, Integer GPSUnCheck_ID, String TaskStart_TM, String TaskEnd_TM, String Query_DT, Integer Round_NR, String ShiftName_TX, String GPSPoint_ID, String ShiftGroupName_TX, Integer Post_ID, String Post_CD, String PostName_TX, Integer Appuser_ID, String AppUser_CD, String AppUserName_TX, String Complete_CD, String Complete_TM, Integer CheckUser_ID, String CheckUser_TX, Integer CheckUserPost_ID, String ISMemo_YN, String Memo_TX, String AuditUserName_TX, String Audit_DT, String XXResult_TX, String XXDesc_TX) {
        this.XXUncheck_ID = XXUncheck_ID;
        this.Partition_ID = Partition_ID;
        this.GpsXXItem_ID = GpsXXItem_ID;
        this.GPSUnCheck_ID = GPSUnCheck_ID;
        this.TaskStart_TM = TaskStart_TM;
        this.TaskEnd_TM = TaskEnd_TM;
        this.Query_DT = Query_DT;
        this.Round_NR = Round_NR;
        this.ShiftName_TX = ShiftName_TX;
        this.GPSPoint_ID = GPSPoint_ID;
        this.ShiftGroupName_TX = ShiftGroupName_TX;
        this.Post_ID = Post_ID;
        this.Post_CD = Post_CD;
        this.PostName_TX = PostName_TX;
        this.Appuser_ID = Appuser_ID;
        this.AppUser_CD = AppUser_CD;
        this.AppUserName_TX = AppUserName_TX;
        this.Complete_CD = Complete_CD;
        this.Complete_TM = Complete_TM;
        this.CheckUser_ID = CheckUser_ID;
        this.CheckUser_TX = CheckUser_TX;
        this.CheckUserPost_ID = CheckUserPost_ID;
        this.ISMemo_YN = ISMemo_YN;
        this.Memo_TX = Memo_TX;
        this.AuditUserName_TX = AuditUserName_TX;
        this.Audit_DT = Audit_DT;
        this.XXResult_TX = XXResult_TX;
        this.XXDesc_TX = XXDesc_TX;
    }

    public Integer getXXUncheck_ID() {
        return XXUncheck_ID;
    }

    public void setXXUncheck_ID(Integer XXUncheck_ID) {
        this.XXUncheck_ID = XXUncheck_ID;
    }

    public Integer getPartition_ID() {
        return Partition_ID;
    }

    public void setPartition_ID(Integer Partition_ID) {
        this.Partition_ID = Partition_ID;
    }

    public Integer getGpsXXItem_ID() {
        return GpsXXItem_ID;
    }

    public void setGpsXXItem_ID(Integer GpsXXItem_ID) {
        this.GpsXXItem_ID = GpsXXItem_ID;
    }

    public Integer getGPSUnCheck_ID() {
        return GPSUnCheck_ID;
    }

    public void setGPSUnCheck_ID(Integer GPSUnCheck_ID) {
        this.GPSUnCheck_ID = GPSUnCheck_ID;
    }

    public String getTaskStart_TM() {
        return TaskStart_TM;
    }

    public void setTaskStart_TM(String TaskStart_TM) {
        this.TaskStart_TM = TaskStart_TM;
    }

    public String getTaskEnd_TM() {
        return TaskEnd_TM;
    }

    public void setTaskEnd_TM(String TaskEnd_TM) {
        this.TaskEnd_TM = TaskEnd_TM;
    }

    public String getQuery_DT() {
        return Query_DT;
    }

    public void setQuery_DT(String Query_DT) {
        this.Query_DT = Query_DT;
    }

    public Integer getRound_NR() {
        return Round_NR;
    }

    public void setRound_NR(Integer Round_NR) {
        this.Round_NR = Round_NR;
    }

    public String getShiftName_TX() {
        return ShiftName_TX;
    }

    public void setShiftName_TX(String ShiftName_TX) {
        this.ShiftName_TX = ShiftName_TX;
    }

    public String getGPSPoint_ID() {
        return GPSPoint_ID;
    }

    public void setGPSPoint_ID(String GPSPoint_ID) {
        this.GPSPoint_ID = GPSPoint_ID;
    }

    public String getShiftGroupName_TX() {
        return ShiftGroupName_TX;
    }

    public void setShiftGroupName_TX(String ShiftGroupName_TX) {
        this.ShiftGroupName_TX = ShiftGroupName_TX;
    }

    public Integer getPost_ID() {
        return Post_ID;
    }

    public void setPost_ID(Integer Post_ID) {
        this.Post_ID = Post_ID;
    }

    public String getPost_CD() {
        return Post_CD;
    }

    public void setPost_CD(String Post_CD) {
        this.Post_CD = Post_CD;
    }

    public String getPostName_TX() {
        return PostName_TX;
    }

    public void setPostName_TX(String PostName_TX) {
        this.PostName_TX = PostName_TX;
    }

    public Integer getAppuser_ID() {
        return Appuser_ID;
    }

    public void setAppuser_ID(Integer Appuser_ID) {
        this.Appuser_ID = Appuser_ID;
    }

    public String getAppUser_CD() {
        return AppUser_CD;
    }

    public void setAppUser_CD(String AppUser_CD) {
        this.AppUser_CD = AppUser_CD;
    }

    public String getAppUserName_TX() {
        return AppUserName_TX;
    }

    public void setAppUserName_TX(String AppUserName_TX) {
        this.AppUserName_TX = AppUserName_TX;
    }

    public String getComplete_CD() {
        return Complete_CD;
    }

    public void setComplete_CD(String Complete_CD) {
        this.Complete_CD = Complete_CD;
    }

    public String getComplete_TM() {
        return Complete_TM;
    }

    public void setComplete_TM(String Complete_TM) {
        this.Complete_TM = Complete_TM;
    }

    public Integer getCheckUser_ID() {
        return CheckUser_ID;
    }

    public void setCheckUser_ID(Integer CheckUser_ID) {
        this.CheckUser_ID = CheckUser_ID;
    }

    public String getCheckUser_TX() {
        return CheckUser_TX;
    }

    public void setCheckUser_TX(String CheckUser_TX) {
        this.CheckUser_TX = CheckUser_TX;
    }

    public Integer getCheckUserPost_ID() {
        return CheckUserPost_ID;
    }

    public void setCheckUserPost_ID(Integer CheckUserPost_ID) {
        this.CheckUserPost_ID = CheckUserPost_ID;
    }

    public String getISMemo_YN() {
        return ISMemo_YN;
    }

    public void setISMemo_YN(String ISMemo_YN) {
        this.ISMemo_YN = ISMemo_YN;
    }

    public String getMemo_TX() {
        return Memo_TX;
    }

    public void setMemo_TX(String Memo_TX) {
        this.Memo_TX = Memo_TX;
    }

    public String getAuditUserName_TX() {
        return AuditUserName_TX;
    }

    public void setAuditUserName_TX(String AuditUserName_TX) {
        this.AuditUserName_TX = AuditUserName_TX;
    }

    public String getAudit_DT() {
        return Audit_DT;
    }

    public void setAudit_DT(String Audit_DT) {
        this.Audit_DT = Audit_DT;
    }

    public String getXXResult_TX() {
        return XXResult_TX;
    }

    public void setXXResult_TX(String XXResult_TX) {
        this.XXResult_TX = XXResult_TX;
    }

    public String getXXDesc_TX() {
        return XXDesc_TX;
    }

    public void setXXDesc_TX(String XXDesc_TX) {
        this.XXDesc_TX = XXDesc_TX;
    }

}
